### ISSUE TITLE
train.f.gb contains different number of genes?

### ISSUE THREAD

**Issue by kataksk** [Gaius-Augustus/BRAKER#125]
I used braker2 (ver. 2.1.4) twice, but in different date with basically same parameters.
First, I ran braker2 like this:

`/path-to/braker.pl --genome=/path-to/genome.fa --bam=/path-to/sort.bam --species=XXX --cores=30 --AUGUSTUS_ab_initio --softmasking --gff3 --workingdir=/path-to/braker_RNAseq --GENEMARK_PATH=/path-to/gmes_petap`

In this case, version of GeneMark should have been 4.4.6 or 4.4.7.

After several days, I reinstalled GeneMark and ran braker2 again.
In this case, version of GeneMark is 4.4.8.
Now, I have gotten the different number of reliable training genes.
In the braker2 with GeneMark 4.4.8, I got lesser number of that than with 4.4.6 or 4.4.7., and failed to complete running.

Is it possible?

**Comment by tomasbruna** [comment]
Hello,

your observation is correct, the output file format of GeneMark changed between versions 4.46 and 4.47. It contains additional information in the last gff column which is causing the problem you observed.

This problem is fixed here https://github.com/Gaius-Augustus/Augustus/commit/c21845d95a9928afa6c6ed5e7a41a4a3ada9eac2 and the fix will be included in the next BRAKER2 release.

To fix the issue now, you can either:

Update the `filterGenesIn_mRNAname.pl` script in Augustus as it was done here https://github.com/Gaius-Augustus/Augustus/commit/c21845d95a9928afa6c6ed5e7a41a4a3ada9eac2

or:

Remove the additional information from GeneMark output with this bash command:
```bash
sed "s/_t\";.*/_t\";/" genemark.gtf > genemark_compatible.gtf
```
   and  re-run BRAKER with `--geneMarkGtf=genemark_compatible.gtf` option to use the compatible output.

Tomas

**Comment by tomasbruna** [comment]
@KatharinaHoff, since this issue seems to be common, do you think we could prepare a new release of BRAKER/Augustus which would include this fix?

Alternatively, if you want to wait with the release (until more features/fixes are added), we could temporarily remove the additional features from GeneMark output in the latest release to keep the tools compatible.

**Comment by KatharinaHoff** [comment]
We will make a new release this week.

**Comment by kataksk** [comment]
@tomasbruna @KatharinaHoff Thank you very much!!

**Comment by KatharinaHoff** [comment]
Finally made the release. Apologies that it took so long.
