### ISSUE TITLE
train.f.gb empty

### ISSUE THREAD

**Issue by diriano** [Gaius-Augustus/BRAKER#126]
My train.f.gb file was empty. But I had plenty of good genes from RNASeq data. It turned out a problem in Augustus-3.3.3/scripts/filterGenesIn_mRNAname.pl that was not parsing correctly the transcript names.

I changed the line

   if ( $_ =~ m/transcript_id \"(.*)\";/ ) {

for this one

  if ( $_ =~ m/transcript_id \"([0-9_t]*)\"/ ) {

And now I have genes in train.f.gb

**Comment by phyden** [comment]
Hi,

I observed the same issue. This also matches the observations in #125 
The reason is apparently, that GeneMark-ES version 4.48 adds some more attributes after the `transcript_id` such as `cds_type` and `count`, which it did not in version 4.47. This is due to the very unspecific wildcard in the regex `.*`. It expands to everything between two double quotes, and therefore the extracted transcript_id string will not match the `gene_id` in the genbank file anymore.

Using an older version of GeneMark-ES would also be a solution, but there is no source where they can be obtained (at least I could not find any) and it's never a good idea to rely on older software unless there is a very good reason for this.

br,
Patrick

**Comment by KatharinaHoff** [comment]
I hope so.
