### ISSUE TITLE
error for fix_in_frame_stop_codon_genes.py

### ISSUE THREAD

**Issue by ovidp** [Gaius-Augustus/BRAKER#127]
My error may be related to #71, but I am using augustus 3.3.3 which should contain already the fix for it. I am running braker 2.1.4 with splicing hints from RNAseq and protein sequences. The run has failed at this info in braker.log:

Mon Dec  2 16:23:23 2019: fixing AUGUSTUS genes with in frame stop codons...
/apps/python3/3.7.0/bin/python3 /apps/augustus/3.3.3/scripts/fix_in_frame_stop_codon_genes.py -g /scratch/braker/genome.fa -t /scratch/braker/augustus.Ppri5.gtf -b /scratch/braker/bad_genes.lst -o augustus.Ppri5_fix_ifs_ -s DincBr6 -m on --UTR off --print_utr off -a /scratch/config -C /apps/cdbfasta/1.00 -A /apps/augustus/3.3.3/bin -S /apps/augustus/3.3.3/scripts -H /scratch/braker/hintsfile.gff.Ppri5 -e /apps/braker/2.1.4/scripts/cfg/gth.cfg  > /scratch/braker/fix_in_frame_stop_codon_genes_augustus.Ppri5.log 2> /scratch/braker/errors/fix_in_frame_stop_codon_genes_augustus.Ppri5.err

fix_in_frame_stop_codon_genes_augustus.Ppri5.log is empty, and the last file written was fix_IFS_log_qqvkrgxr  which ends with:

Trying to execute the following command:
/usr/bin/grep scaffold522_925473 /scratch/braker/hintsfile.gff.Ppri5
Suceeded in executing command.
Error in file /apps/augustus/3.3.3/scripts/fix_in_frame_stop_codon_genes.py at line 243: Return code of subprocess was 1['/usr/bin/grep', 'scaffold522_925473', '/scratch/braker/hintsfile.gff.Ppri5']

Thanks

_Originally posted by @ovidp in https://github.com/Gaius-Augustus/BRAKER/issues/71#issuecomment-560465508_

**Comment by ovidp** [comment]
Cloning Augustus directly from Github instead of downloading it solves the issue.

**Comment by michieitel** [comment]
I just encountered the same issue even after cloning the latest Augustus (yesterday) from the GitHub page. 

the file fix_IFS_log_gnljxydd shows the following error:

> Trying to execute the following command:
> /bin/grep ONT_TR_PE_scaff_320 /home/ubuntu/avas/braker2/HYPO/corrected_reads/braker2_Aphrocallistes_RAVEN_assembly-1_5kb_corrected_reads.hypo_L_RNA_scaffolded_ONT_TR_PE_sorted.Racon-PE_softmasked/hintsfile.gff
> Suceeded in executing command.
> Error in file /home/ubuntu/tools/anaconda3/envs/braker2/bin/fix_in_frame_stop_codon_genes.py at line 243: Return code of subprocess was 1['/bin/grep', 'ONT_TR_PE_scaff_320', '/home/ubuntu/avas/braker2/HYPO/corrected_reads/braker2_Aphrocallistes_RAVEN_assembly-1_5kb_corrected_reads.hypo_L_RNA_scaffolded_ONT_TR_PE_sorted.Racon-PE_softmasked/hintsfile.gff']
> 

I checked and indeed for ONT_TR_PE_scaff_320 there is no entry in the hintsfile.gff, which is probably due to the fact that only a few random RNA reads map to this region. I guess augustus ab initio predicted a gene that has no RNAseq support, which is true for a lot of genes due to the nature of RNA evidence. However, this should not lead to a crash of the pipeline? In fact for other assemblies the braker2 pipeline finishes successfully. Only some assemblies cause problems.

Any ideas?

Thanks
Michael
