### ISSUE TITLE
output gtf and not gff

### ISSUE THREAD

**Issue by lfaino** [Gaius-Augustus/BRAKER#129]
Dear developer,
i noticed that braker output is a gft file and not anymore a gff file. Can you explain why this change and how i can revert back to gff3?

cheers
Luigi

**Comment by KatharinaHoff** [comment]
Nothing changed regarding the gff3 output: there is a flag --gff3 that will produce gff3 output files. (Default output has never been gff3, we removed the gff (not gff3) files from default output because the additional information in these files as compared to gtf format was different depending on the mode that BRAKER is run.)

Have a look at https://github.com/Gaius-Augustus/Augustus/issues/74 for using the converter on your existing files.

Katharina
