### ISSUE TITLE
What is the difference between the braker and augustus annotation pipelines?

### ISSUE THREAD

**Issue by SSE-Group** [Gaius-Augustus/BRAKER#163]
Sorry if this is a silly question but is braker just a better version of your augustus pipeline?

**Comment by KatharinaHoff** [comment]
AUGUSTUS is a tool for gene prediction. It’s accompanied by some scripts. Some of them have pipeline character (e.g. AutoAug.pl).

BRAKER is a pipeline that automates training of the gene finders GeneMark-ES/ET/EP/EP+ and AUGUSTUS. Since AUGUSTUS usually requires supervised training, GeneMark, which trains in an unsupervised fashion, is very helpful for training AUGUSTUS. BRAKER also takes care of preparing extrinsic evidence for both tools.
