### ISSUE TITLE
Installing BRAKER on a cluster

### ISSUE THREAD

**Issue by realgc** [Gaius-Augustus/BRAKER#164]
Hi,

I'm trying to install BRAKER2 on a cluster, and it would be great if there's a singularity/Decker container. I wonder is there one and if yes could you tell me where to find it?

Many thanks!

**Comment by KatharinaHoff** [comment]
We are currently not maintaining singularity or similar, yet.
What I personally do for clusters: create anaconda environment, install prerequisites, clone BRAKER and AUGUSTUS from github, compile, download GeneMark from Georgia Tech, GenomeThreader from Hamburg, and then get started. I am not using the anaconda BRAKER version because that always takes release from BRAKER and AUGUSTUS - and they are kind of lagging behind because we are slow on making releases.
There is an older Issue that describes Anaconda prerequisites: https://github.com/Gaius-Augustus/BRAKER/issues/22 , post 4.

Good luck :-)

**Comment by npavlovikj** [comment]
I just want to add to this that for each bioconda package, there is a respective biocontainer created, https://bioconda.github.io/recipes/braker2/README.html, that can be used with Singularity.
