### ISSUE TITLE
AUGUSTUS Segmentation fault

### ISSUE THREAD

**Issue by ookil** [Gaius-Augustus/BRAKER#17]
While using BRAKER I keep getting such error:

`braker.pl --genome=/media/damian/Toshiba/Canu_Pilon.fasta --esmode
Logfile: /home/damian/Programs/BRAKER-master/braker/Sp_4/braker.log!
ERROR in file /home/damian/Programs/BRAKER-master/scripts/braker.pl at line 6556
Failed to execute: perl /home/damian/Programs/Augustus/scripts/optimize_augustus.pl --rounds=5 --species=Sp_4 --kfold=8 --AUGUSTUS_CONFIG_PATH=/home/damian/Programs/Augustus/config/ --onlytrain=/home/damian/Programs/BRAKER-master/braker/Sp_4/train.gb.train.train /home/damian/Programs/BRAKER-master/braker/Sp_4/train.gb.train.test 1>/home/damian/Programs/BRAKER-master/braker/Sp_4/optimize_augustus.stdout 2>/home/damian/Programs/BRAKER-master/braker/Sp_4/errors/optimize_augustus.stderr!`

And this is stdout and stderr 
`Splitting training file into 8 buckets...
Reading in the meta parameters used for optimization from /home/damian/Programs/Augustus/config/species/generic/generic_metapars.cfg...
Reading in the starting meta parameters from /home/damian/Programs/Augustus/config/species/Sp_4/Sp_4_parameters.cfg...
bucket `

`Segmentation fault (core dumped)
Could not read the accuracy values out of predictions.txt when processing bucket 1. at /home/damian/Programs/Augustus/scripts/optimize_augustus.pl line 1128.`

any idea what may be the reason?

**Comment by KatharinaHoff** [comment]
Please update to the latest version from github. This problem occurs when
the number of training genes is huge (which happens on complex genomes in
esmode).

I already implemented downsampling a couple of commits ago.

**Comment by ookil** [comment]
Sadly I still get the same error

**Comment by KatharinaHoff** [comment]
That's a surprise. Would you be so kind as to share the files 

/home/damian/Programs/BRAKER-master/braker/Sp_4/train.gb.train.train /home/damian/Programs/BRAKER-master/braker/Sp_4/train.gb.train.test 

with us? I'll try reproduce the problem with your data. I have much bigger data sets that lead to the same phenomenon, but everytime that I shrink them, I cannot reproduce the error, anymore.

**Comment by ookil** [comment]
Of course, I emailed them to you.

**Comment by KatharinaHoff** [comment]
I was unable to reproduce the problem with ookil's files on our servers. However, I have seen the exact same error message, before. It appears to be system configuration dependent?

**Comment by koonimaru** [comment]
Is this issue solved? I got the same error, and found a solution at least in my situation (that took a week).
The problem was augustus that optimize_augustus.pl used. My computer has a system-wide augustus and a locally compiled one. Although I set  --AUGUSTUS_BIN_PATH as the local one when running BRAKER, optimize_augustus.pl seemed to use the system-wide augustus. 

A quick solution was edit 'aug_exec_dir' of line 35 in optimize_augustus.pl to use the local augustus directory. I hope this works for you too.

**Comment by KatharinaHoff** [comment]
This will not solve the problem for all users, regrettably.

**Comment by koonimaru** [comment]
Come on, I am not talking about all users' problem, but ookil's one. Indeed, this is a bug, right? When I tested BRAKER on a computer that did not have globally installed augustus, optimize_augustus.pl did not find a local augustus that I specified. That suggests that ookil's computer may also have a globally-installed augustus. And, optimize_augustus.pl has a problem to find correct augustus.

**Comment by KatharinaHoff** [comment]
If this user is lucky, that will solve the problem. But I can reproduce the
problem with a properly compiled version of AUGUSTUS (and making sure that
optimize finds these binaries) on several of our machines - not with her
exact data, as I already stated. So: maybe your solution is a fix for her,
maybe not. Let us know, ookil, will you?

**Comment by cgjosephlee** [comment]
I got same problem here. Simply add `--aug_exec_dir=$AUGUSTUS_BIN_PATH` around https://github.com/Gaius-Augustus/BRAKER/blob/master/scripts/braker.pl#L6822 to specify augustus path for `optimize_augustus.pl` can do the trick.

**Comment by KatharinaHoff** [comment]
Great. That solves it for users where the problem actually was that the augustus binary could not be located. (There still remains an optimize_augustus.pl issue where the binary is clearly available; I will leave that issue open in AUGUSTUS repository since BRAKER automatically limits the number of training genes in order to avoid this problem.) https://github.com/Gaius-Augustus/BRAKER/commit/a36ce6e065fb8a0b10e820b31971b9a653eda9f0
