### ISSUE TITLE
missing RNAseq.bam from examples

### ISSUE THREAD

**Issue by phanousk** [Gaius-Augustus/BRAKER#2]
There is a missing test file so test1.sh can not be completed. BTW would it be possible to have shorter tests or make the computations parallel at least?

**Comment by phanousk** [comment]
Sorry, my fault that I did't read the main readme properly. I am going to download the .bam file as suggested. Could you please mention that also in readme for the examples?

**Comment by KatharinaHoff** [comment]
The RNA-Seq Bam-file is hosted, separately, due to its size. This is stated
in the README file at
https://github.com/Gaius-Augustus/BRAKER/blob/master/README.TXT

We can’t change that large files need to be hosted in a separate place. We
also can’t build tiny test data because braker is a pipeline for annotating
entire genomes. A significantly high number of training genes is required
to run all tools in braker.

You can adapt the braker tests to run on multiple cores (e.g. —cores=8). We
will not put this as default setting because not all users want to run
braker on more than one core.
