### ISSUE TITLE
Question about the estimation time cost of run test2.sh

### ISSUE THREAD

**Issue by bam2wigKillMe** [Gaius-Augustus/BRAKER#215]
In Braker's README.md, the estimation time cost of run test2.sh is just 24min, but to run the test2_restart1.sh, the estimation time cost is 84min!!!

And when I ran the test2.sh for 101m29.663s which is far more than the estimated 24min, so i thought the test2.sh is already finished, so i pressed "ctrl "+" c". Then i check the test2.log, in the end of the log,  its time record showed it was still running when I forced it to stop.

So I hope you can adjust the estimation of test2.sh, or kindly explain to me why.

BIG THANKYOU for answers.
Best wished to you.

**Comment by tomasbruna** [comment]
Hello, you are correct, test2.sh now takes much longer than it used to (it now took 3 hours on my machine with 8 CPU cores), due to some changes in the code. These changes will probably also cause a mismatch between the test output and the expected output. Thanks for bringing this to our attention.

Tomas

**Comment by tomasbruna** [comment]
I am closing this issue for now -- will create a new one to fix all of the affected tests.
