### ISSUE TITLE
Gene names

### ISSUE THREAD

**Issue by grexor** [Gaius-Augustus/BRAKER#238]
More a question than an issue, how does braker name genes in the final braker.gtf file?

I get something like this:

```
chr       AUGUSTUS        gene    1776597 1777779 0.45    +       .       g642592
chr       AUGUSTUS        transcript      1776597 1777779 0.45    +       .       g642592.t1
chr       AUGUSTUS        exon    1777668 1777779 .       +       .       transcript_id "file_1_file_1_g642592.t1"; gene_id "file_1_file_1_g642592";
```

Now the gene record g642592 is fine, however where is the "file_1_file_1_g642592" coming from? Shouldn't it be just g642592?

Thanks, Gregor

**Comment by KatharinaHoff** [comment]
No, it should not just be g642592, since that gene might separately exist. It should be file_1_file_1_g642592.

These funny names result for merging gene sets from different files. Admittedly, the names are not very beautiful but easy to track while debugging.

We are no using TSEBRA and this issue does not apply, anymore.
