### ISSUE TITLE
Spaln second iteration

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [Gaius-Augustus/BRAKER#240]
Hi,
I am running braker (2.1.5) in the epmode with protein_seq as hints using spaln 2.3.3. The prothint version is 2.4.0. We are running into the issue that prothint throws the following error at the start of iteration 2.

ProtHint exited due to an error in command: grep stop_codon Spaln/spaln.gff > stops.gff

Let me know if there is any fix for this.

Thanks!
Benjamin

**Comment by tomasbruna** [comment]
Hello Benjamin,

I think this issue happens when no additional hints are found by ProtHint in the second iteration. I will fix this in ProtHint soon.

Right now, you can disable the problematic second iteration with `--skipIterativePrediction` option. Since the error is likely caused by the lack of additional hints in the second iteration, it should not have any negative effect on the result.

Best,
Tomas
