### ISSUE TITLE
Ridiculous introns occur in BRAKER result

### ISSUE THREAD

**Issue by AlexWanghaoming** [Gaius-Augustus/BRAKER#261]
Dear developer, 
I use BRAKER on fungus genome, I noticed that some introns of unknown origin occur in result file. I upload them in the attach files.
![Error1](https://user-images.githubusercontent.com/28863445/91875980-c6ae5580-ecae-11ea-8777-26e0f322c4da.png)
![Error2](https://user-images.githubusercontent.com/28863445/91875989-c8781900-ecae-11ea-8a18-b85fe3f323a5.png)
![Error3](https://user-images.githubusercontent.com/28863445/91875992-c910af80-ecae-11ea-9427-abc78d380674.png)
![Error4](https://user-images.githubusercontent.com/28863445/91875996-ca41dc80-ecae-11ea-91c2-1ad7a1b2b314.png)
Just as you can see in IGV browser, the first track is RNA-seq reads, the GTF files from top to bottom are final GTF from BRAKER2 in pipeline Figure 5, GeneMark_ES.gtf and GeneMark_ETP.gtf.
I noticed that some of incorrect introns come from only several reads spliced in a highly expressed gene. And some of them have no source. I run BRAKER2 using parameters as below:
`braker.pl --fungus --cores 14 --etpmode --softmasking --gff3 --genome=$MASKED_GENOME --prot_seq=${ortho_protein} --bam=fj11_hypha_1.sorted.bam`
I do not know whether parameters could be optimized? Or are there any other strategies I can employ?
Thanks,
Alex

**Comment by AlexWanghaoming** [comment]
My BRAKER2 version is 2.1.5 installed from conda

**Comment by KatharinaHoff** [comment]
Both AUGUSTUS and GeneMark must not necessarily see any evidence support in order to predict in an intron. Both tools try to predict a likely and possible gene model - and if there is a need to insert an intron in order to create this model, they do it.

GeneMark only uses evidence in prediction in the novel version of GeneMark-EP (to my knowledge this is only working with protein evidence at the moment, but @tomasbruna may contradict here). If you ran GeneMark with RNA-Seq evidence, it will only have used RNA-Seq data during training and not during prediction. This explains your observation.

**Comment by tomasbruna** [comment]
To add to Katharina's correct explanation:

All GeneMarks use the evidence during training. GeneMark-EP and -ETP also use protein evidence (and a combination of protein and RNA evidence in case of ETP) directly in predictions. Thus, some of the introns not supported (or weakly supported) by RNA-Seq can have protein support and that is why they were predicted.
