### ISSUE TITLE
Empty evidence.gff when using --hints and --prothints

### ISSUE THREAD

**Issue by apredeus** [Gaius-Augustus/BRAKER#269]
Hello, 

I'm trying to run the following command: 

`braker.pl --genome=$GENOME --hints=$HINTS --prothints=$PHINT --softmasking --etpmode --gff3 --cores 32`

I've taken RNA-seq hints from the previous Braker2 run, and prepared protein hints using ProtHint. The latter run generated `evidence.gff` without any problem (alongside with much bigger `prothint_augustus.gff`). However, when I'm using both RNA-seq hintfile and `prothint_augustus.gff` as a protein hintfile with Braker2, it fails when running GeneMark-EX (from logs, path replaced with <path> for brevity):

`perl ~/gmes_linux_64/gmes_petap.pl --verbose --seq <path>/braker/genome.fa --max_intergenic 50000 --evidence <path>/braker/evidence.gff --et_score 10 --ET <path>/braker/genemark_hintsfile.gff --cores=32 --gc_donor 0.001 --soft_mask 1000 1><path>/braker/GeneMark-ETP.stdout 2><path>/braker/errors/GeneMark-ETP.stderr`

I'm pretty sure it fails because of the empty `evidence.gff` file. 

When I've tried a similar command but with proteins fasta, the run failed even earlier - despite me having ProtHint properly installed and added to `$PATH`

What could be the reason for this? Thank you in advance.

**Comment by tomasbruna** [comment]
Hello,

we've recently updated (and improved) the way ProtHint is integrated with BRAKER2. I assume you are using an older version because the option `--prothints` is no longer present (you can use ProtHint hints directly with `--hints` option), and the GeneMark call is slightly different in the current version.

Please obtain the latest version of BRAKER2 (with `git clone` from the master branch) and of ProtHint, the problems should be resolved. I recommend starting with the [test3.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test3.sh) to make sure everything is working.

Best,
Tomas

**Comment by apredeus** [comment]
Thank you very much. I'll try to use the latest Braker2 from the repo. So far I've been using version 2.1.5 installed from conda. 

Do I understand correctly that I can just concatenate Braker-formatted hints from RNA-seq and ProtHint and use the combined file with `--hints`?

**Comment by tomasbruna** [comment]
> Do I understand correctly that I can just concatenate Braker-formatted hints from RNA-seq and ProtHint and use the combined file with --hints?

You can do that (use the `prothint_augustus.gff` output of the latest ProtHint), or you can also supply RNA-Seq hints and protein.fasta file, BRAKER2 will take care of calling ProtHint in such case.
