### ISSUE TITLE
ProtHint error (no topProt found in Spaln/spaln.gff)

### ISSUE THREAD

**Issue by holmrenser** [Gaius-Augustus/BRAKER#281]
I am running braker in `--etpmode` with rna-seq evidence and swissprot proteins as protein evidence. The run crashes with the following error:

```
error: ProtHint exited due to an error in command: grep topProt=TRUE Spaln/spaln.gff > topProteins.gff
```

Any tips?

**Comment by KatharinaHoff** [comment]
Try to run with OrthoDB. Swissprot probably didn’t generate sufficient high
quality alignments.

Katharina

**Comment by holmrenser** [comment]
That is an interesting suggestion, thanks! Is there any documentation on what is considered a high quality alignment somewhere? 

As a suggestion: perhaps a more meaningful error message could be used if this step fails. I could submit a PR if you're interested.

**Comment by KatharinaHoff** [comment]
I believe the GeneMark-EP paper covers the alignment quality.

We will look into whether the error message needs to be improved in
ProtHint or BRAKER.

**Comment by tomasbruna** [comment]
Hello Rens,

it is possible that the problem with swissprot was caused by the presence of some special characters in the fasta headers of the protein input file. I've recently fixed this issue (https://github.com/gatech-genemark/ProtHint/commit/b6575bf553f32a36d19290c8f790b9b400807bd4). In any case, using OrthoDB should be a better option since there are more proteins.

> As a suggestion: perhaps a more meaningful error message could be used if this step fails.

Thanks for the suggestion, I've updated ProtHint to fail with an informative error message in case a similar problem occurs (https://github.com/gatech-genemark/ProtHint/commit/4585738337d21f9ba0243de08935ff79124271e2).

Best,
Tomas

**Comment by holmrenser** [comment]
Thanks for the fix! I'm definitely going to try it out since I'm interested in what is required to come up with an accurate annotation. I plan on doing a comparison of swissprot VS orthodb to see what is annotated differently.

In the end I managed to get an initial annotation with orthodb, so for me this issue can be closed.

**Comment by tomasbruna** [comment]
Thanks for the update!

**Comment by aditi17142** [comment]
Hi!!
I am running ProtHint 
and wrote the command
  ./prothint.py genome.fasta proteins.fasta  --geneSeeds /home/yeastbiofuel/Desktop/GenomeAnnotation/ProtHint/dependencies/genemark.gtf --workdir test

Error: Inflate error.
[Wed Mar 10 11:22:30 2021] error: ProtHint exited due to an error in command: /home/yeastbiofuel/Desktop/GenomeAnnotation/ProtHint/bin/../dependencies/diamond makedb --in /home/yeastbiofuel/Desktop/GenomeAnnotation/ProtHint/bin/test/prot3maor19_ -d diamond_db --threads 16


Please help in fixing the error.
Thank you.

**Comment by tomasbruna** [comment]
Hmm, I have not seen this before, this looks like a problem with DIAMOND. Can you share the file `/home/yeastbiofuel/Desktop/GenomeAnnotation/ProtHint/bin/test/prot3maor19_` (or upload it somewhere if it's too big)? I'll take a look at it and I'll try to run DIAMOND, maybe there is something unexpected in your input.

**Comment by aditi17142** [comment]
Thank you for replyinh.
I was able to rectify it. You are right, there was an issue with the input protein file.
