### ISSUE TITLE
Getting braker.gtf output from BRAKER v2.1.4 [Mac OS X]

### ISSUE THREAD

**Issue by SentientFish** [Gaius-Augustus/BRAKER#292]
I am using BRAKER on Mac OS X and, after getting some issues with the currently outdated version of GeneMarkES that is the only one available available on Mac, I switched to BRAKER v2.1.4 according to recommendations here: https://github.com/Gaius-Augustus/BRAKER/issues/175?email_token=AJMC6JB6PWNQ7ME27WHAN3DRFAGFLA5CNFSM4K5BMQD2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IQ4RNPQ

Thankfully BRAKER v2.1.4 ran successfully. However, I am using a pipeline (https://github.com/CompSynBioLab-KoreaUniv/FunGAP) that looks for a braker.gff3 as the output of BRAKER. Per the v2.1.5 release notes it seems that this output was added in this version so I cannot get it directly with my version. I looked through the v2.1.5 code to try to get the braker.gff3 output and this is what I came up with

`merge_transcript_sets.pl augustus.hints.gtf GeneMark-ET/genemark.gtf > braker.gtf`

`gtf2gff.pl --gff3 --printExon <braker.gtf --out=braker.gff3`

Please let me know if this is an okay workaround or if I need to do more with this output.

Here was my braker.pl command, by the way:
`braker.pl --fungus --softmasking --cores=22 --genome=/Users/pierrj/fungap_runs/guy11/fungap_out/maker_out/masked_assembly.fasta.adjusted --bam=/Users/pierrj/fungap_runs/guy11/fungap_out/hisat2_out/SRR8842990.bam --species=SRR8842990_2 --gff3 --AUGUSTUS_CONFIG_PATH=/Users/pierrj/anaconda3/envs/fungap/bin/../config --BAMTOOLS_PATH=/Users/pierrj/anaconda3/envs/fungap/bin --GENEMARK_PATH=/Users/pierrj/fungap_local/FunGAP/external/gm_et_macosx/gmes_petap --SAMTOOLS_PATH=/Users/pierrj/anaconda3/envs/fungap/bin --workingdir=/Users/pierrj/fungap_runs/guy11/fungap_out/braker_out/SRR8842990  --translation_table=1 --AUGUSTUS_BIN_PATH=/Users/pierrj/anaconda3/envs/fungap/bin > /Users/pierrj/fungap_runs/guy11/fungap_out/logs/braker_SRR8842990.log 2>&1`

**Comment by tomasbruna** [comment]
Hello,

your command needs one small adjustment. We use only a subset of confident genes (supported by external evidence) from GeneMark-ET.

To do that, replace

    merge_transcript_sets.pl augustus.hints.gtf GeneMark-ET/genemark.gtf > braker.gtf

with 

    merge_transcript_sets.pl augustus.hints.gtf GeneMark-ET/genemark.f.multi_anchored.gtf > braker.gtf

The rest looks good!

Tomas

**Comment by SentientFish** [comment]
Great, thank you!

**Comment by pierrj** [comment]
I was able to get BRAKER v2.1.5 to work on my Mac by playing around with different versions of GeneMark-ES. I posted the way I did this in the thread I linked above but I figured I would post it here as well in case someone comes across this thread:

1) Download both Mac OS X and Linux 64 versions of GeneMark-ES
2) Compile Gibbs3 because the included version only works on 32bit Mac OS. To do this, untar and unzip gibbs-3.1.tar.gz in the GeneMark-ES for Mac OS directory. Then compile. Here is the command I used for this:
`sudo make CC='/usr/local/Cellar/gcc/10.2.0/bin/gcc-10' CFLAGS="-Wunused-but-set-variable"`
Finally replace old Gibbs3 with the new compiled one.
3) In the directory containing the Linux 64 versions of GeneMark-ES, replace the following executables with the ones of the same name in your Mac OS X version directory: Gibbs3, gmhmme3 and probuild.

Now you should be able to run gmes_petap.pl from the Linux 64 directory through BRAKER on your Mac just fine. Hope this helps other people out there that were stuck on this issue!

**Comment by jdavidpeery** [comment]
Could you use merge_transcript_sets.pl to combine the braker.gtf files from multiple BRAKER runs?

I have RNA-seq data from multiple different experiments and a recently assembled genome, all from the same species. I was wondering if I could run BRAKER multiple times, using the RNA-seq data from a different experiment each time, then merge the annotations at the end using merge_transcript_sets.pl .

**Comment by tomasbruna** [comment]
Hello @jdavidpeery,

you can supply multiple BAM files from different experiments to a single BRAKER run, as illustrated here https://github.com/Gaius-Augustus/BRAKER#braker-with-rna-seq-data.

If you want to run BRAKER multiple times and then combine the results, I would recommend using the newly developed [TSEBRA combiner tool](https://github.com/Gaius-Augustus/TSEBRA), described in [this paper](https://www.biorxiv.org/content/10.1101/2021.06.07.447316v1).

Best,
Tomas
