### ISSUE TITLE
Failing during optimize_augustus.pl

### ISSUE THREAD

**Issue by OnlyHigh** [Gaius-Augustus/BRAKER#30]
Hey, it's me again,
I tried to generate a model for my species and during the optimize_augustus.pl, I got the following error:
``` 
bio@biocomp04:~/Documents/Purpureocillium/March2019$ perl /home/bio/apps/augustus-3.3.2/scripts/optimize_augustus.pl --rounds=5 --species=Purp --kfold=8 --AUGUSTUS_CONFIG_PATH=/home/bio/apps/augustus-3.3.2/config --onlytrain=/home/bio/Documents/Purpureocillium/March2019/braker/Purp/train.gb.train.train --cpus=8 /home/bio/Documents/Purpureocillium/March2019/braker/Purp/train.gb.train.test
Splitting training file into 8 buckets...
Reading in the meta parameters used for optimization from /home/bio/apps/augustus-3.3.2/config/species/generic/generic_metapars.cfg...
Reading in the starting meta parameters from /home/bio/apps/augustus-3.3.2/config/species/Purp/Purp_parameters.cfg...
bucket Segmentation fault (core dumped)
2 Segmentation fault (core dumped)
Segmentation fault (core dumped)
3 Segmentation fault (core dumped)
8 5 Segmentation fault (core dumped)
1 Segmentation fault (core dumped)
6 Segmentation fault (core dumped)
Segmentation fault (core dumped)
4 7 Could not read the accuracy values out of predictions.txt when processing bucket 1. at /home/bio/apps/augustus-3.3.2/scripts/optimize_augustus.pl line 1224.
```
Later I used the following command, and Braker2 executed perfectly, 

```
bio@biocomp04:~/Documents/Purpureocillium/March2019$ ~/apps/BRAKER-2.1.2/scripts/braker.pl --genome=./working-genomes/Purp-polished-abyss.fasta.masked --bam=./Purp-annotation/Purp-RNAseq-to-genome-unmasked.bam --species=Purp --cores=4 --AUGUSTUS_CONFIG_PATH=/home/bio/apps/augustus-3.3.2/config --GENEMARK_PATH=/home/bio/apps/gm_et_linux_64/gmes_petap --fungus --skipOptimize --useexisting
```

What do you think it could be, 
Am I executing it wrong? 
Cheers, 
Luis Alfonso.

**Comment by KatharinaHoff** [comment]
Hi Alfonso,

we have seen optimize_augustus.pl fail in two cases: first, when the
AUGUSTUS binary cannot be located (
https://github.com/Gaius-Augustus/BRAKER/issues/17), second, when the
number of training genes is very large (
https://github.com/Gaius-Augustus/Augustus/issues/42). I guess that you
actually have augustus installed in

/home/bio/apps/augustus-3.3.2/bin/augustus

because the BRAKER command ran ok. Can you count how many genes are in
/home/bio/Documents/Purpureocillium/March2019/braker/Purp/train.gb.train.train
and /home/bio/Documents/Purpureocillium/March2019/braker/Purp/train.gb.train.test
(grep -c LOCUS gb-file).

Thanks,

Katharina

**Comment by OnlyHigh** [comment]
Hi Katarina, 
Apparently the issue raised because I had two versions of augustus and one of was not suitable for the analysis, 

Cheers, 
Luis Alfonso.
