### ISSUE TITLE
Some questions about the GeneMark-ES

### ISSUE THREAD

**Issue by Huangyizhong** [Gaius-Augustus/BRAKER#320]
Hi,
The braker is a good software to do the prediction of new genome. I downloaded it recently to do the prediction. But I have a problem about the codes to conduct the GeneMark-ES. The codes are as follows:
![image](https://user-images.githubusercontent.com/31943359/107341177-9db1ac80-6af9-11eb-916b-0ea82314dc65.png)
I am confused about it and need help!
Thanks so much in advance!
Best wishes to you 

huangyizhong

**Comment by tomasbruna** [comment]
Hello Huangyizhong,

the problem seems to be caused by the Perl [Hash::Merge](https://metacpan.org/pod/Hash::Merge) module. GeneMark-ES crashes on line 16 in the `build_mod.pl` script when it tries to import this module.

Can you try to re-install the module, or install it in a different way?

You can probably test whether the module imports correctly (without running GeneMark-ES) by using the following command

```
perl -e 'use Hash::Merge qw( merge );'
```

Best,
Tomas

**Comment by Huangyizhong** [comment]
Thaks so much, I will try it.
















At 2021-02-11 06:17:42, "Tomáš Brůna" <notifications@github.com> wrote:

Hello Huangyizhong,

the problem seems to be caused by the Perl Hash::Merge module. GeneMark-ES crashes on line 16 in the build_mod.pl script when it tries to import this module.

Can you try to re-install the module, or install it in a different way?

You can probably test whether the module imports correctly (without running GeneMark-ES) by using the following command

perl -e 'use Hash::Merge qw( merge );'


Best,
Tomas
