### ISSUE TITLE
Failing to concatenate gff files

### ISSUE THREAD

**Issue by KSS92** [Gaius-Augustus/BRAKER#333]
Hello, I am trying to use BRAKER 2.1.5 with my soft masked canu assembly and a .bam file generated with raw RNA-seq data and gsnap . However I consistently get the following error:

`cat: /dss/dssfs02/lwp-dss-0001/pn69xe/pn69xe-dss-0000/di52zuz/Projects/Hindistincta/braker2/braker/tmp_merge_hints.gff: No such file or directory`
`cat: /dss/dssfs02/lwp-dss-0001/pn69xe/pn69xe-dss-0000/di52zuz/Projects/Hindistincta/braker2/braker/tmp_no_merge_hints.gff: No such file or directory`
`ERROR in file /dss/dssfs02/lwp-dss-0001/pn69xe/pn69xe-dss-0000/di52zuz/Apps/BRAKER/scripts/braker.pl at line 6155`
`Failed to execute: cat /dss/dssfs02/lwp-dss-0001/pn69xe/pn69xe-dss-0000/di52zuz/Projects/Hindistincta/braker2/braker/tmp_merge_hints.gff /dss/dssfs02/lwp-dss-0001/pn69xe/pn69xe-dss-0000/di52zuz/Projects/Hindistincta/braker2/braker/tmp_no_merge_hints.gff > /dss/dssfs02/lwp-dss-0001/pn69xe/pn69xe-dss-0000/di52zuz/Projects/Hindistincta/braker2/braker/hintsfile.temp.gff`

 I have run test1.sh without issue so I believe my installation is correct. Is this an issue with my own data or my pathing?

[braker_MIIG_1388.log](https://github.com/Gaius-Augustus/BRAKER/files/6089572/braker_MIIG_1388.log)
[braker_test1.log](https://github.com/Gaius-Augustus/BRAKER/files/6089573/braker_test1.log)

**Comment by tomasbruna** [comment]
Hello @KSS92 ,

looking at the code, it seems like this error happens when no intron hints are extracted from the bam file. I was able to reproduce the same error when I used a bam file with a single unspliced read in the `test1.sh`. Please check your bam -- are there any introns?

The program should not fail like this when this happens. Function `join_mult_hints()` crashes when the `$to_be_merged` file is empty. Instead, it should warn the user and exit properly. I will open a separate issue regarding this problem.

Best,
Tomas

**Comment by KSS92** [comment]
Hello Tomas,

Thank you for your advice. I determined that my gsnap parameters were actually incorrect. When I redid the mapping and used the new .bam file braker ran without issue.

Thanks!
Kenneth

**Comment by tomasbruna** [comment]
Hi Kenneth,

thanks for letting me know, glad it's fixed. Also, thanks for reporting this, I've updated the code to print a more user-friendly message when a situation like yours occurs.

Best,
Tomas

**Comment by laura-valencia** [comment]
Hello @KSS92 
I have this problem too, and I wondered if you could share your gsnap commands. I cannot get my BAM files right.

Best regards.
