### ISSUE TITLE
braker.gtf's size shrinks sharply after adding the arg --augustus_args="--hintsfile=total.hintsfile.gff"

### ISSUE THREAD

**Issue by bam2wigKillMe** [Gaius-Augustus/BRAKER#339]
Hello,
I ran into a problem when I ran BRAKER with the arg '--augustus_args="total.hintsfile.gff"'.
When I didn't add the arg, I got braker.gtf file with a size of about 120Mb, but after I add the arg, the braker.gtf is only 21Mb.

I was meant to let some relatively unreliable evidence to only participate the prediction step of AUGUSTUS, so I add the unreliable evidence to rnaseq to be the total.hintsfile.gff with '--augustus_args="--hintsfile=total.hintsfile.gff"'used.

The full command is like:
`braker.pl --cores=8 --gff3 \
--genome=genome.fa.masked --softmasking \
--hints=rnaseq.hintsfile.gff \
--augustus_args="--hintsfile=total.hintsfile.gff" \
--workingdir=out
`

Any guidance would be appreciated!
Best wishes!

**Comment by tomasbruna** [comment]
Hello,

here is my theory why this approach does not work and how to make it work.

### Likely cause of the problem

When you pass additional arguments to Augustus with `--augustus_args`, they will get passed exactly as specified on the command line without any pre-processing. Because BRAKER changes its working dir during execution, the relative path to the hintsfile (`total.hintsfile.gff`) won't really point to anything and this can cause all sorts of unexpected behavior.

Using an absolute path (`--augustus_args="--hintsfile=/path/to/total.hintsfile.gff"`) should fix this, but even then, Augustus would get two `--hintsfile` arguments: one with `/path/to/total.hintsfile.gff` and one with internally processed hints from `--hints=rnaseq.hintsfile.gff`. I am not sure what happens when `--hintsfile` is specified twice like this or if this behavior is even defined.

### Solution

The best way to achieve what you want would be to train BRAKER with `rnaseq.hintsfile.gff` and then to run a prediction step with `total.hintsfile.gff`.

This can be done as follows:

1. Training step
```
braker.pl --cores=8 --gff3 --genome=genome.fa.masked --softmasking --hints=rnaseq.hintsfile.gff --workingdir=out --species=speciesName
```

2.  Prediction step
```
braker.pl --cores=8 --gff3 --genome=genome.fa.masked --softmasking --hints=total.hintsfile.gff --workingdir=outPrediction --species=speciesName --skipAllTraining
```

Note that it's important to specify `species=speciesName` so that BRAKER knows how to connect the training and prediction steps.

Best,
Tomas

**Comment by bam2wigKillMe** [comment]
Thank you so much for your helpful guidance! I will try it now, 

but I just got one little question from your answer: if without --augustus_arg="--hintsfile=total.hintsfile.gff", like 
`braker.pl --cores=8 --gff3 \ --genome=genome.fa.masked --softmasking \ --hints=rnaseq.hintsfile.gff  \ --workingdir=out`
then I check the braker.log, it records commands that show augustus will NOT use the arg "--hints=rnaseq.hintsfile.gff" in this case, here is the log about augustus prediction step:
`# Wed Mar  3 16:31:07 2021: creating AUGUSTUS jobs (with hints)
cd $wd
perl ~/augustus-3.3.3/scripts/createAugustusJoblist.pl --sequences=$wd/aug_hints.lst --wrap="#!/bin/bash" --overlap=5000 --chunksize=1252500 --outputdir=$wd/augustus_tmp --joblist=$wd/hints.job.lst --jobprefix=aug_hints_ --partitionHints --command "~/augustus-3.3.3/config/../bin/augustus --species=Sp_38 --AUGUSTUS_CONFIG_PATH=~/augustus-3.3.3/config --extrinsicCfgFile=~/braker/scripts/cfg/rnaseq.cfg --alternatives-from-evidence=true --UTR=off --exonnames=on --codingseq=on --allow_hinted_splicesites=gcag,atac  --softmasking=1" 2>...
`
and if I add the arg --augustus_arg="--hintsfile=total.hintsfile.gff" to a braker run, then the log shows augustus WILL use the arg "--hints=rnaseq.hintsfile.gff", so do this mean that in a normal braker run with only RNAseq data, the prediction step of augustus would not use the RNAseq data which only participates steps before this step? If that's true, then you should modify Figure 3 of braker's readme.md because it says the opposite way.

Thank you again for your reply!
Best!

**Comment by bam2wigKillMe** [comment]
Thank you so much for your helpful guidance! I will try it now, 

but I just got one little question from your answer: if without --augustus_arg="--hintsfile=total.hintsfile.gff", like 
`braker.pl --cores=8 --gff3 \ --genome=genome.fa.masked --softmasking \ --hints=rnaseq.hintsfile.gff  \ --workingdir=out`
then I check the braker.log, it records commands that show augustus will NOT use the arg "--hints=rnaseq.hintsfile.gff" in this case, here is the log about augustus prediction step:
`# Wed Mar  3 16:31:07 2021: creating AUGUSTUS jobs (with hints)
cd $wd
perl ~/augustus-3.3.3/scripts/createAugustusJoblist.pl --sequences=$wd/aug_hints.lst --wrap="#!/bin/bash" --overlap=5000 --chunksize=1252500 --outputdir=$wd/augustus_tmp --joblist=$wd/hints.job.lst --jobprefix=aug_hints_ --partitionHints --command "~/augustus-3.3.3/config/../bin/augustus --species=Sp_38 --AUGUSTUS_CONFIG_PATH=~/augustus-3.3.3/config --extrinsicCfgFile=~/braker/scripts/cfg/rnaseq.cfg --alternatives-from-evidence=true --UTR=off --exonnames=on --codingseq=on --allow_hinted_splicesites=gcag,atac  --softmasking=1" 2>...
`
and if I add the arg --augustus_arg="--hintsfile=total.hintsfile.gff" to a braker run, then the log shows augustus WILL use the arg "--hints=rnaseq.hintsfile.gff", so do this mean that in a normal braker run with only RNAseq data, the prediction step of augustus would NOT use the RNAseq data which only participates steps before this step? If that's true, then you should modify Figure 3 of braker's readme.md because it says the opposite way.

Thank you again for your reply!
Best!

**Comment by tomasbruna** [comment]
The command here specified by `--command` is not the final command used to execute AUGUSTUS. The script `createAugustusJoblist.pl` modifies it according to additional arguments. The hints are added through these additional arguments (via `--sequences=$wd/aug_hints.lst`). You may notice that the genomic sequence itself is not part of the base command, it is also added through this script.
