### ISSUE TITLE
Works with metagenome ?

### ISSUE THREAD

**Issue by michoug** [Gaius-Augustus/BRAKER#345]
Hi,
I got a metagenome assembly (filtered by Eukrep (https://github.com/patrickwest/EukRep)) and was wondering if BRAKER would be adapted for its annotation? If yes, which parameters would you choose?
Best
Greg

**Comment by tomasbruna** [comment]
Hi Greg,

I think it should be possible with some data pre-processing. The [EukRep paper](https://genome.cshlp.org/content/28/4/569.full.pdf+html) actually gives some guidance:

_After benchmarking EukRep on reference data sets, the algorithm was applied to the CG_WC sample, and 214.8 Mbps of scaffold sequence was classified as eukaryotic. Because eukaryotic gene predictors are designed to be trained and run on a single genome at a time, CONCOCT (Alneberg et al. 2014), an automated binning algorithm, was applied to the identified eukaryotic scaffolds to generate two preliminary eukaryote genomes. In this way, GeneMark-ES and AUGUSTUS gene prediction could be performed, as described above, on each bin individually as if running on a single genome._

Instead of using GeneMark-ES and AUGUSTUS, BRAKER2 (which actually combines the two) could be used. You can run BRAKER2 in the protein mode (https://github.com/Gaius-Augustus/BRAKER#braker-with-proteins-of-any-evolutionary-distance), with OrthoDB eukaryotic proteins on input. Here is a guide on protein database preparation: https://github.com/gatech-genemark/ProtHint#protein-database-preparation. You might want to combine different protein sets, depending on your expectations.

Best,
Tomas

**Comment by KatharinaHoff** [comment]
I used BRAKER2 to predict genes in MAGs. It worked well. You have to make
sure that you separate the contigs into species as good as possible.

**Comment by michoug** [comment]
Thanks a lot for the answers, I tried it for some of the MAGs, however, it failed for many of them (>10Mb) because of a lack of training data in GeneMark-ES, probably because they are too fragmented. Any idea, how to resolve this issue?

**Comment by tomasbruna** [comment]
Try using BRAKER's `--min_contig` parameter. This adjusts the minimum contig length used in GeneMark training. The default is set to 50 Kbp.

**Comment by KatharinaHoff** [comment]
What sequencing technology did you use?

**Comment by michoug** [comment]
Novaseq

**Comment by KatharinaHoff** [comment]
Ok. Then you might not be able to improve the assembly much...

**Comment by KatharinaHoff** [comment]
@michoug, is this still an open issue?

If you continue to face a lack for training data, you could try https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/augustify.py to pick the most suitable parameter set from a set of existing species parameters in order to set a starting parameter set. (50% of augustify picking runs fail, but this is captured, and you don't need the predictions for all contigs since you already species-binned them.)

Then you can try iterative training according to https://math-inf.uni-greifswald.de/storages/uni-greifswald/fakultaet/mnf/mathinf/stanke/augustus_wrp.pdf in order to adapt parameters to each MAG.
