### ISSUE TITLE
GeneMark Error

### ISSUE THREAD

**Issue by psur9757** [Gaius-Augustus/BRAKER#347]
I am running BRAKER on a bunch of genomes that I have downloaded from NCBI. All of them except this one finishes. 

Script
```
#Load software
module load augustus/3.3.4 genemark-es/4.64 samtools/1.11 diamond/2.0.4 cdbfasta/1.00 gushr/1.0.0 ucsc-userapps/390
export PATH=/scratch/obligates/bin/BRAKER/scripts/:$PATH
export PROTHINT_PATH=/usr/local/genemark-es/4.64/ProtHint/bin

#Setting up Augustus
export AUGUSTUS_CONFIG_PATH=/scratch/obligates/bin/augustus_v3.3.4_config
export AUGUSTUS_BIN_PATH=/usr/local/augustus/3.3.4/bin
export AUGUSTUS_SCRIPTS_PATH=/usr/local/augustus/3.3.4/scripts

#Run BRAKER2 with protein sequences
braker.pl --species=PARAC --genome=P.arachidis/2.REPEATMASKER/PARAC.fa.masked --prot_seq=0.scripts.logs/uniprot_odb10.fa --softmasking --cores 8 --fungus --workingdir=P.arachidis/3.BRAKER --gff3
```
- BRAKER was cloned from GitHub master branch on March 24. I want to use this version only if possible, since all other assemblies were processed with it.

Error
```
	The file ~/.gm_key exists and has not been copied.
# Sun Mar 28 15:45:39 2021: Log information is stored in file /scratch/RDS-FSC-obligates-RW/ncbi/1.annotation/P.arachidis/3.BRAKER/braker.log
#*********
# WARNING: Detected whitespace in fasta header of file /scratch/obligates/ncbi/1.annotation/0.scripts.logs/uniprot_odb10.fa. This may later on cause problems! The pipeline will create a new file without spaces or "|" characters and a genome_header.map file to look up the old and new headers. This message will be suppressed from now on!
#*********
#*********
# WARNING: Detected | in fasta header of file /scratch/obligates/ncbi/1.annotation/0.scripts.logs/uniprot_odb10.fa. This may later on cause problems! The pipeline will create a new file without spaces or "|" characters and a genome_header.map file to look up the old and new headers. This message will be suppressed from now on!
#*********
#*********
# WARNING: in file /scratch/obligates/bin/BRAKER/scripts/braker.pl at line 1341
file /scratch/RDS-FSC-obligates-RW/ncbi/1.annotation/P.arachidis/3.BRAKER/genome.fa contains a highly fragmented assembly (130300 scaffolds). This may lead to problems when running AUGUSTUS via braker in parallelized mode. You set --cores=8. You should run braker.pl in linear mode on such genomes, though (--cores=1).
#*********
ERROR in file /scratch/obligates/bin/BRAKER/scripts/braker.pl at line 6585
Failed to execute: perl /usr/local/genemark-es/4.64/gmes_petap.pl --verbose --cores=8 --ES --gc_donor 0.001 --sequence=/scratch/RDS-FSC-obligates-RW/ncbi/1.annotation/P.arachidis/3.BRAKER/genome.fa  --fungus --soft_mask auto 1>/scratch/RDS-FSC-obligates-RW/ncbi/1.annotation/P.arachidis/3.BRAKER/GeneMark-ES.stdout 2>/scratch/RDS-FSC-obligates-RW/ncbi/1.annotation/P.arachidis/3.BRAKER/errors/GeneMark-ES.stderr
The most common problem is an expired or not present file ~/.gm_key!
```
- The file `~/.gm_key!` absolutely exists. All the other BRAKER runs complete. It is not expired either.

Let me know if you need any other information. Thank you for your help.

**Comment by tomasbruna** [comment]
Hello,

> The file ~/.gm_key! absolutely exists. All the other BRAKER runs complete. It is not expired either.

Yes, the `gm_key` warning message always pops up when GeneMark fails, I'm sure it's something else in your case.

Probably the problem is related to the fragmentation of your assembly (the log file says there are 130,300 scaffolds).

I have some ideas about what's causing this issue, can you share the following log files?

- `/scratch/RDS-FSC-obligates-RW/ncbi/1.annotation/P.arachidis/3.BRAKER/errors/GeneMark-ES.stderr`
- `/scratch/RDS-FSC-obligates-RW/ncbi/1.annotation/P.arachidis/3.BRAKER/GeneMark-ES.stdout`
- `/scratch/RDS-FSC-obligates-RW/ncbi/1.annotation/P.arachidis/3.BRAKER/GeneMark-ES/gmes.log`

There should be some useful information to help me debug this issue.

Tomas

**Comment by psur9757** [comment]
Hi Tomas,

The files you requested: 
[GeneMark-ES.stderr.txt](https://github.com/Gaius-Augustus/BRAKER/files/6232866/GeneMark-ES.stderr.txt)
[GeneMark-ES.stdout.txt](https://github.com/Gaius-Augustus/BRAKER/files/6232868/GeneMark-ES.stdout.txt)
[gmes.log.txt](https://github.com/Gaius-Augustus/BRAKER/files/6232871/gmes.log.txt)


GeneMark-ES.stderr mentions "not enough data". My guess is it is not referring to the genome size (87M).
 

Best,
Priyanka

**Comment by tomasbruna** [comment]
Hello Priyanka,

this problem is indeed caused by the fragmentation of the genome. By default, GeneMark only uses contigs longer than 50 Kbp for training. For this input, none of the contigs is longer than that.

You can adjust the minimum contig length used in training with BRAKER's parameter `--min_contig=INT`. Using something like `10000` should work fine; but please check what % of the genome is in the contigs longer than 10,000. Ideally, you want to include at least 50% of the sequence in training.

Related to that, it might be a good idea to check the other genomes as well. If they were similarly fragmented, it is possible that BRAKER was trained only on a small subset of the genome -- if, for example, only one contig out of many was longer than 50k.

Best,
Tomas

**Comment by psur9757** [comment]
Hi Tomas,

I checked all of my assemblies. Only 33% have half the sequence greater than 50KB. And 60% have half the sequence greater than 10KB. The problematic genome is 1% greater than 10KB, see statistics below:
```
Main genome scaffold total:         	130300
Main genome scaffold sequence total:	87.617 MB
% main genome in scaffolds > 50 KB: 	0.00%


Minimum 	Number        	Number        	Total         	Total         	Scaffold
Scaffold	of            	of            	Scaffold      	Contig        	Contig  
Length  	Scaffolds     	Contigs       	Length        	Length        	Coverage
--------	--------------	--------------	--------------	--------------	--------
   5 KB 	           375	           375	     2,895,021	     2,895,021	 100.00%
  10 KB 	            59	            59	       819,243	       819,243	 100.00%
  25 KB 	             3	             3	        91,136	        91,136	 100.00%
```

Example of one of the fragmented assemblies I have managed to complete with the script above. It has 4% genome greater than 10KB.
```
Main genome contig total:           	53459
Main genome contig sequence total:  	62.683 MB  	8.634% gap
% main genome in scaffolds > 50 KB: 	0.00%

Minimum 	Number        	Number        	Total         	Total         	Scaffold
Scaffold	of            	of            	Scaffold      	Contig        	Contig  
Length  	Scaffolds     	Contigs       	Length        	Length        	Coverage
--------	--------------	--------------	--------------	--------------	--------
   5 KB 	         2,123	         5,648	    15,660,302	    13,073,088	  83.48%
  10 KB 	           274	           920	     3,365,074	     2,558,150	  76.02%
  25 KB 	             1	             7	        26,402	        25,488	  96.54%
```

I am going try with `--min_contig=10000` for any failed BRAKER runs. Thank you for the advice.
