### ISSUE TITLE
The hints file is empty. Maybe the genome and the RNA-seq file do not belong together

### ISSUE THREAD

**Issue by naktang** [Gaius-Augustus/BRAKER#36]
I'm try to run braker with the following code below
perl /home/chutima/wat_work_2/software/BRAKER/scripts/braker.pl --genome ref.fasta --bam=gmap_isoseq_sort.bam --BAMTOOLS_PATH=/home/chutima/wat_work_2/software/bamtools/bin/ --AUGUSTUS_CONFIG_PATH=/home/chutima/wat_work_2/software/Augustus/config/ -cores=10 --gff3 -AUGUSTUS_ab_initio --SAMTOOLS_PATH=/home/chutima/wat_work_2/software/samtools-1.9/

this is the header of bam file
c404_f29p8_2075c404	16	tig00000954_quiver	388229	40	4S395M82N108M126N87M106N81M79N135M98N222M106N81M109N162M96N191M100N142M124N96M99N139M659

This is the header of fasta file
>tig00000954_quiver
AAGTTAATAATCCTTCCCCTGAATTAAAACAATTGTCTGCTCACCTACGTTATGCTTTCTTAGGAGAATCTTCTACTTTC
CAGTTATCATTTCAAAATGATTTAAGTAAAGAAGAAGAGGAAAAATTGTTGGATGTGTTAAAAAAGCATAAATCTGCCTT

I think both file have the same header name. Do you have any suggestion why that error happen.

**Comment by SvitlanaLukicheva** [comment]
Hello,

I had a similar problem and I had to patch the headers of my fasta file to make them correspond to the headers of the bam file.

In your case: the bam header is "c404_f29p8_2075c404 16 tig00000954_quiver 388229 40" and the fasta header is "tig00000954_quiver". So you should patch the first file in order to make the headers correspond to the second file (and thus have "tig00000954_quiver" in both files).

**Comment by longzhangnation** [comment]
you can try to change another alignment software ,such as STAR. anyway, it works for me .

**Comment by KatharinaHoff** [comment]
Yes, it is easiest to use an alignment tool that doesn't modify your
headers. STAR or Hisat2 work well in this context. (Or you have to path the
headers as suggested by Svitlana.)

Katharina
