### ISSUE TITLE
Test2 error

### ISSUE THREAD

**Issue by esolares** [Gaius-Augustus/BRAKER#364]
Hi I have downloaded the rnaseq.bam file but I am having trouble running test2 in the examples. I am getting the following errors.
Unknown option: gc_donor
Value "auto" invalid for option soft_mask (number expected)

**Comment by tomasbruna** [comment]
Hello,

The `gc_donor` and `soft_mask auto` options are relatively new in GeneMark. Please make sure you are working with the latest GeneMark-ES/ET/EP (from http://exon.gatech.edu/GeneMark/license_download.cgi).

Best,
Tomas

**Comment by esolares** [comment]
Hi Tomas

I have downloaded a newer version of GeneMark ES/ET/EP and have rebuilt my install. I am now getting empty hint file errors on test1.sh 

Edwin

**Comment by esolares** [comment]
Hi Tomas,

I have been able to get BRAKER to work now, but still fails the tests. I did however had to install other CPAN libraries. Do you all have a plan to get a docker image setup?

Thank you,

Edwin

**Comment by tomasbruna** [comment]
Hello Edwin,

> I have been able to get BRAKER to work now, but still fails the tests

please report the error messages from the failed tests here, I'll try to help.

> Do you all have a plan to get a docker image setup?

 There is a docker image available for the latest BRAKER2 release through Bioconda at https://bioconda.github.io/recipes/braker2/README.html. However, it still required a separate installation of GeneMark-ES/ET/EP which cannot be included due to some licensing issues. There are plans to improve this in the future.

Best,
Tomas
