### ISSUE TITLE
Alternative Transcripts input and output question

### ISSUE THREAD

**Issue by jasonstevenson2256** [Gaius-Augustus/BRAKER#40]
Does the --alternatives_from_evidence=true require a separate hints file supplied in the command script or will it use the ones generated by GeneMark in the output directory? I ran two jobs, one with this command and one without, the one without had more predicted genes listed in the output gtf/gff file. Does this command take alternative transcripts into account when predicting genes or will should it give an output file of alternate transcripts? Should I include this command when predicting genes from an unannotated non-model organism?

Secondly, I have a question about the predicted genes output. Several genes have the suffix t1, t2 etc., (e.g. g55.t1, g55.t2) do these indicate alternate transcripts/isoforms?

Thank you

**Comment by KatharinaHoff** [comment]
--alternatives_from_evidence will use the hints that you - anyway - provide
to BRAKER, for example: the hints form a BAM file, or the hints that are
provided with the --hints=hints.gff option, or the hints that are created
from GenomeThreader alignments. It will not take the output of GeneMark as
"evidence" (that output does not contain alternative transcripts, in any
case).

It is possible that without alternatives from evidence, you predict more
genes because some genes were split into two or more genes in comparison to
prediction with alternatives from transcripts (that's not a  typical
pattern, but probably the reason in your case).

It makes sense to use this option if you have RNA-Seq evidence. For protein
evidence (GaTech protein mapping pipeline), it might also be useful. For
protein evidence (GenomeThreader) I am not sure; it probably depends on how
many alternative protein isoforms you fed into GenomeThreader.

I frequently use alternatives from evidence to annotate novel genomes.

The suffixes t1, t2, t... name alternative transcript isoforms, yes. If you
take an approach where protein and RNA-Seq evidence is mixed, this naming
might not always reflect alternative isoforms, appropriately (in rare
cases).
