### ISSUE TITLE
Setting AUGUSTUS_BIN_PATH fails at bam2hints

### ISSUE THREAD

**Issue by ralowe** [Gaius-Augustus/BRAKER#41]
Setting the AUGUSTUS_BIN_PATH variable causes an issue with bam2hints as it looks for this in bin/ this results in an incorrect path. Removing bin from AUGUSTUS_BIN_PATH fails with couldn't find AUGUSTUS.

`AUGUSTUS_BIN_PATH =/opt/augustus-3.2.3/bin`
Command that fails
`/opt/augustus-3.2.3/bin/bin/bam2hints --intronsonly --in=/data/scratch/user/STAR_Aligned.out.bam --out=/data/scratch/user/braker/Sp_1/bam2hints.temp.gff 2>/data/scratch/user/braker/Sp_1/errors/bam2hints.0.stderr
`

**Comment by KatharinaHoff** [comment]
In line 4521 of the current code version, the path to bam2hints is set as follows:

$augpath = "$AUGUSTUS_BIN_PATH/bam2hints";

$AUGUSTUS_BIN_PATH itself is set in function set_AUGUSTUS_BIN_PATH(), starting in line 1520. It is either taken from an environment variable (errors could potentially occur there if the path is set incorrectly), or from explicit command line argument (errors could potentially occur there if the path is set incorrectly), or from relative location to an existing $AUGUSTUS_CONFIG_PATH (usually fail safe). I think I fixed the error of "bin/bin" during some earlier commit.

I close the issue because this seems to have been fixed, already.
