### ISSUE TITLE
Why do not use wiggle track without --UTR=on?

### ISSUE THREAD

**Issue by xiekunwhy** [Gaius-Augustus/BRAKER#476]
Hi,

I just want to know why braker pipeline do not use wiggle track when doing code-gene prediction (without adding UTRs), wiggle exonpart may cause some bad affect ?

Best,
Kun

**Comment by KatharinaHoff** [comment]
Gene expression coverage occurs in all parts of transcripts (protein-coding
part, non-coding part = UTR). If you add hints from coverage data and
predict genes without a UTR model, you run a risk to predict overly long
and wrong CDS because AUGUSTUS will not know that coverage could
potentially also occur in noncoding parts of transcripts.

**Comment by xiekunwhy** [comment]
Hi @KatharinaHoff ,

Thank you very much for your reply, and I understand now.

Best,
Kun
