### ISSUE TITLE
Output of test1.sh deviates from example results

### ISSUE THREAD

**Issue by rotoke** [Gaius-Augustus/BRAKER#482]
Dear BRAKER developers,

I ran `test1.sh`to test my local BRAKER installation on our HPC cluster. As far as I can tell, the script finishes without errors, but the files produced do not match the example results:

```
compare_intervals_exact.pl --f1 augustus.hints.gtf --f2 ../../results/test1/augustus.hints.gtf --verbose
# CDS in file augustus.hints.gtf: 1433
# CDS in file ../../results/test1/augustus.hints.gtf: 1454

#in	match	unique	%match	CDS

1433	1304	129	91.00	augustus.hints.gtf
1454	1304	150	89.68	../../results/test1/augustus.hints.gtf
```

```
compare_intervals_exact.pl --f1 augustus.hints.gtf --f2 ../../results/test1/augustus.hints.gtf --trans --verbose
# Transcripts-CDS in file augustus.hints.gtf: 271
# After removal of duplications:
# Transcripts-CDS in file augustus.hints.gtf: 271
# Transcripts-CDS in file ../../results/test1/augustus.hints.gtf: 269
# After removal of duplications:
# Transcripts-CDS in file ../../results/test1/augustus.hints.gtf: 269

#in	match	unique	%	Transcript-CDS

271	197	74	72.69	augustus.hints.gtf
269	197	72	73.23	../../results/test1/augustus.hints.gtf
```

I understand that the process is somewhat stochastic, but I doubt that the output should vary by more than 1-2%. First I thought it may be due to changes in `RNAseq.bam` as it's 164MB rather than 134MB on my system, but re-running `test1.sh`with the option `--hints=../RNAseq.hints` gave the same result. BRAKER and dependencies were installed according to the guidelines (perl and perl modules via conda, rest as indicated).  Versions are as follows:

```
braker.pl version 2.1.6
AUGUSTUS (3.4.0)
Python 3.8.5
openjdk version "1.8.0_322"
gushr.py 1.0.0
GeneMark-ES Suite version 4.69
bamtools 2.4.2
samtools 1.9
diamond version 0.9.24
prothint.py 2.6.0
make_hub.py 1.0.6
```

Do you have any idea what could have gone wrong? I don't really know where to start troubleshooting this, but I'm happy to provide more outputs and information if you let me know where or what to look for.

Thank you,
Roman

**Comment by tomasbruna** [comment]
Hi Roman,

thanks for reporting this issue. There was a recent change in GeneMark which is causing this difference, I am actually getting the same result as you are with the new GeneMark version.

I was not aware that this change in GeneMark was already pushed to production -- I will update all the tests so that the reference outputs are matching results with the new GeneMark version.

On real datasets (much bigger than the example), the change in GeneMark does not affect the final BRAKER results that much -- the change is in the expected 1-2% range and it seems to be in a positive direction (towards better accuracy).

Best,
Tomas
