### ISSUE TITLE
 the full-length transcriptome (PB) data enconunter problems

### ISSUE THREAD

**Issue by ld9866** [Gaius-Augustus/BRAKER#492]
Dear software developer:
Thank you very much for developing such good software!
We have recently encountered some problems with the software and it is very confusing to us.
We used your newly published full-length transcriptome for the final result integration, but the effect left us very confused.
The results of our integration using the results from braker1 and brake2 are excellent, with 22,000 genes and 21,000 functional annotations of encoded protein sequences, which is in line with our species.
But when we added the full-length transcriptome (PB) data, we found that the number of predicted genes reached 25,000, which far exceeded our prediction. We felt that the credibility of this was relatively low, and we solved this problem. It's been a long time but there is still no way to lower it.
The EVidenceModeler we obtained from the literature may solve our problem, but we don't know how to input the results of the braker to this software, mainly gene_predictions.gff3, protein_alignments.gff3 and transcript_alignments.gff3 which correspond to our brake1 and brake2 respectively What are the results? Is there a reference range for the weight setting?
good luck!

**Comment by KatharinaHoff** [comment]
We usually don't use EvidenceModeler with BRAKER because it cannot handle the evidence from BRAKER. https://github.com/Gaius-Augustus/TSEBRA can do this. TSEBRA does have a longreads branch: https://github.com/Gaius-Augustus/TSEBRA/tree/long_reads

A lot depends on how you call the genes in the PacBio transcripts. We usually run GeneMarkS-T, but this alone returns noisy gene models, some of them look truncated, etc. GeneMark development team at GeorgiaTech recommends to filter the predicted genes by protein homology to database proteins. It's likely a good idea.

I will close this issue because we cannot provide support on EvidenceModeler.
