### ISSUE TITLE
braker with diamond

### ISSUE THREAD

**Issue by mictadlo** [Gaius-Augustus/BRAKER#52]
Hi @npavlovikj,
Could you please build a new Braker package which contains Diamond as a replacement 
of Blast ( https://github.com/Gaius-Augustus/BRAKER/issues/25 )?

Thank you in advance,

Best wishes,

Michal

**Comment by npavlovikj** [comment]
Thanks for the update Michal! 
@KatharinaHoff , can you please tag a new release of Braker so I can try and update the conda recipe? Looks like there have been some improvements since 2.1.2, so minor or major release will be sufficient for me to update the current conda recipe.

**Comment by KatharinaHoff** [comment]
The current code has a bug in ETP mode, which is why I am holding back on a
release.

**Comment by npavlovikj** [comment]
Thanks for the prompt reply @KatharinaHoff ! Whenever there is a new release, please feel free to ping me for update on the conda recipe.

@mictadlo , I hope you are ok waiting for the official release for an update. In the meantime, you can create your custom conda environment with all the dependencies and patches as in the current `braker2` recipe, https://github.com/bioconda/bioconda-recipes/tree/c986913bdef74f38d1754fb2f4e10ad28f32c8b6/recipes/braker2, just instead of using the release tarball, please use `git clone` so you can pick up the newest changes.

**Comment by KatharinaHoff** [comment]
I will close this issue since we already have https://github.com/Gaius-Augustus/BRAKER/issues/22 concerning BRAKER on conda.
