### ISSUE TITLE
Too little genes predicted

### ISSUE THREAD

**Issue by SamCT** [Gaius-Augustus/BRAKER#526]
Hello,

I have been running BRAKER1 and BRAKER2 with two respective sets of data: 1) raw RNA-seq data of various tissue types from the species aligned to the masked genome via hisat2, with a .bam file of ~450 million reads on average; and 2) a large protein set of conserved genes Viridiplantae (odb10) and publicly available annotated gene sets of the same species of my plant (~55,000 genes), consisting of ~3.5 million proteins total. 

Following TSEBRA combine, I'm consistently getting numbers ~22,000-24,000 genes. Most of the literature published, using MAKER, is ~28,000 genes. What makes me question the data set is twofold: comparing the new Braker set to a previous MAKER annotation set (~34,000 genes) of a lower-quality assembly from the same individual, I'm getting a match of ~50% shared genes between the sets, but most of the matches are partial (not complete gene copies). In the specific region I'm looking at, I have blastn results showing that all the genes (complete) are present from the previous MAKER annotation, but these annotations are not being produced by my new BRAKER runs. 

Is there something wrong with my approach? Wondering how I can address this significant issue. 

Here are my two commands:

Protein:
braker.pl --cores 8 --genome=my_genome.hap1.p_ctg.fasta.masked --softmasking --epmode --gff3 --AUGUSTUS_ab_initio --prot_seq=Large_protFile.complete.fasta

RNA:
braker.pl --cores 8 --genome=my_genome.hap1.p_ctg.fasta.masked --softmasking --gff3 --AUGUSTUS_ab_initio --bam=Aligned_to_maskGenomeHisat2_sorted.bam

TSEBRA:

tsebra.py -g /PROTEIN/braker/augustus.hints.gtf,/RNA/braker/augustus.hints.gtf -c default.cfg -e /PROTEIN/braker/hintsfile.gff,/RNA/braker/hintsfile.gff -o braker_final_combined.gtf

Thank you,
Sam

**Comment by KatharinaHoff** [comment]
It kinds of sounds like you want to map a gene set from a previous assembly to the current assembly. Transmap would be an appropriate tool for the task. The MAKER authors also describe a protocol for mapping annotations in https://currentprotocols.onlinelibrary.wiley.com/doi/10.1002/0471250953.bi0411s48

BRAKER runs a self-training GeneMark-ES to generate seeds for protein to genome seed alignments with DIAMOND, and for good hits, this is refined with Spaln. In a second iteration, seeds from ab initio AUGUSTUS are added. This means that even if you put the entire set of proteins from your old assembly on top of e.g. OrthoDB, BRAKER will not generate alignments for some of them, because there was no GeneMark-ES or AUGUSTUS seed for this region. (The seeding is done to save time but yet have high quality spliced alignments; BRAKER uses protein amounts that are too large for other approaches.)

MAKER aligns proteins to genome with Exonerate without such seeds from a gene predictor. The runtime is much higher, so the input protein set must be smaller than what you can use with BRAKER. But a protein set of a single (even the same) species is no significant problem.

BRAKER does not check on coverage across a transcript. The predictions that you get are basically AUGUSTUS and GeneMark predictions that were created with evidence or without. MAKER uses coverage across transcript information. Thus, BRAKER has a tendency for split genes, while MAKER has a small tendency for fused genes.

If it was my project, I'd probably use GenomeThreader with the reference protein set to generate a third gene set, and then I'd enforce that third gene set in TSEBRA. But as stated before, you might want to look into Transmap, instead.

**Comment by SamCT** [comment]
Hello,

Thanks for your response on this, it has been very helpful. I've managed to run GenomeThreader on a reference protein set, independently of BRAKER. This is due to some issues on our infrastructure which we are still working out. GTH generated a gff3 file and the number of genes are close to what I'd expect. It's a difference of nearly 7,000 genes.

In my attempt to enforce the third set with TSEBRA I have encountered some issues, which I believe is due to my standalone run of genomethreader. I've seen some of the braker output log, which deals with a bit of this but not in full detail. First, the hintsfile.gff is composed of only introns and for column 9, a src, multiplicity and other scoring metrics. Obviously, I do not have this information with a raw genomethreader output, which impedes TSEBRA integration. And I have to do a conversion from gff3 to gtf and retain gene,transcript,start_codon,CDS, exon and stop codon -- as well as proper format with respect to gene_id and transcript_id in column 9. Am I forced to run GenomeThreader as an option with BRAKER, or is there a straight forward way to reintegrate the standalone GenomeThreader output for use with TSEBRA?

**Comment by SamCT** [comment]
Happy to report that once GenomeThreader is properly integrated and accessible (we set up a conda environment with braker2 and gth), it is outputting an appropriate hintsfile(s). Once they were combined with TSEBRA (RNA run+gth protein run), I am getting numbers that I would expect (~30,000 genes), with transcript copies that reflect larger parts of my genes of interest. 

I will close this issue now, thank you!
