### ISSUE TITLE
Error while running ProtHint: error: The "topProt=TRUE" flag is missing in the Spaln/spaln.gff

### ISSUE THREAD

**Issue by nitinra** [Gaius-Augustus/BRAKER#532]
Hello,

I am trying to run Braker on multiple genomes and the test dataset and a subset of my genomes run smoothly in Braker. However, some of them stop abruptly after running ProtHint with the error:

`error: The "topProt=TRUE" flag is missing in the Spaln/spaln.gff output file. This issue can be caused by the presence of special characters in the fasta headers of input files. Please remove any special characters and re-run ProtHint. See https://github.com/gatech-genemark/ProtHint#input for more details about the input format.`

I checked my fasta headers and they do not have any special characters: example below:
<img width="773" alt="Screen Shot 2022-09-27 at 10 09 32 PM" src="https://user-images.githubusercontent.com/70153351/192671442-d299c575-ea46-46da-be7d-1c6e824b1665.png">

Here is the command I used: 
`cat /work/nitinr/running/gustatory_evolution/redmask/run1.txt | parallel -j+0 \
braker.pl --genome={} \
--prot_seq=/work/nitinr/odb10_arthropoda_proteins.fa --softmasking --species {.} \
--cores=28 --workingdir=/work/nitinr/running/gustatory_evolution/results/{.} \
--useexisting --makehub --email=ravikanth.nitin@gmail.com`
Here is my  [braker_log.txt](https://github.com/Gaius-Augustus/BRAKER/files/9660884/braker_log.txt), [error file](https://github.com/Gaius-Augustus/BRAKER/files/9660887/0.braker_test_err.txt), [bash_output_file](https://github.com/Gaius-Augustus/BRAKER/files/9660891/0.braker_test_out.txt) and my [fasta file](https://drive.google.com/file/d/1IvWHyXDVGKJcE80pg4fMj-rel2jalEeQ/view?usp=sharing). 

I am confused as to how to solve this issue.

**Comment by sarahfrail** [comment]
I am getting the same error and cannot figure out why. My fasta headers contain nothing but numbers and letters in my input genome and prot_seq file. Same as @nitinra above, my run makes it through the first iteration with no issues and then fails on the second iteration because ProtHint eventually detects that the Spaln/spaln.gff file is empty.  

This is preceded by `Warning: No unique gene seeds were detected in the /scratch/groups/ellenyeh/sfrail/annotation/brakerprot/braker/augustus.hints_iter1.gtf input file. ProtHint will only update seed gene IDs of hints to match the IDs in the new seed gene file.`
augustus.hints_iter1.gtf and augustus.hints_iter1.gff are also empty, which tells me that the original augustus.hints.gtf/gff from iteration 1 might have been empty. I suspect that it may be an issue with the writing of that file though I'm not sure why since no errors are thrown by augustus or anything else until this second iteration. 

Here is my command:
`braker.pl \
--genome=/workdir/organismgenome.fasta.masked \
--species=organism \
--softmasking \
--useexisting \
--gff3 \
--AUGUSTUS_SCRIPTS_PATH=/condaenv/bin \
--GENEMARK_PATH=/workdir/gmes_linux_64 \
--PROTHINT_PATH=/workdir/ProtHint/bin \
--prot_seq=/workdir/protazoa.fasta \
--cores 16`
