### ISSUE TITLE
InterProScan failed because of asterix (*)

### ISSUE THREAD

**Issue by mictadlo** [Gaius-Augustus/BRAKER#56]
Hi,
I tried to run InterProScan with `augustus.hints_utr.aa` but I got this error:

```
You have submitted a protein sequence which contains an asterix (*). This may be from an ORF prediction program. '*' is not a valid IUPAC amino acid character and amino acid sequences which go through our pipeline should not contain it. Please strip out all asterix characters from your sequence and resubmit your search.
```
Is it better to remove `*` (`sed -i 's/\\*//g' augustus.hints_utr.aa`) or replace it by `X` (`sed -i 's/\\*/X/g' augustus.hints_utr.aa`)?

Thank you in advance,

MIchal

**Comment by KatharinaHoff** [comment]
Hi Michal,

there are two things to be considered:

a) AUGUSTUS can predict genes with in-frame stop codons if the putative
stop codon is spliced (i.e. there is an intron inside the stop codon).
AUGUSTUS does not recognize that codon as a stop codon, then.
b) In general, stop codons are not unknown amino acids, but no amino acids.

Considering both, I recommend deleting the star symbols, instead of
replacing them with an X (because the X is an unknown amino acid).

For a small proportion of genes, you might have functional annotations for
only the first part of some proteins, because the tail of the protein is in
fact not part of the gene (that problem with the in-frame stop codons)...
the script getAnnoFastaFromJoingenes.py actually tells you how many and
which genes are affected by this. In case you want to check.

Katharina

**Comment by mictadlo** [comment]
Hi Katharina,
Thank you.

**Comment by mictadlo** [comment]
I think my above sed command should have been ` sed -i.bak 's|\*||g' test.AA.fasta`

**Comment by KatharinaHoff** [comment]
I am not an expert on sed. I am pretty sure the following two alternatives should work, too:

`sed -i "s/\*//g" test.AA.fasta`

or

`cat test.AA.fasta | perl -pe 's/\*//g' > test.AA.noStar.fasta`
