### ISSUE TITLE
Error: fileparse(): need a valid pathname at .../BRAKER/scripts/braker.pl line 2334.

### ISSUE THREAD

**Issue by msinghgb** [Gaius-Augustus/BRAKER#58]
Hi,
I get this error message when I run BRAKER. 
The bit from braker.pl that seems to to prompting this is:

<img width="735" alt="braker_pl_—__Volumes_abt2_projects_ag-swart-blepharisma_data_gene_prediction_braker_S952_BRAKER_scripts" src="https://user-images.githubusercontent.com/42932418/61135952-f0148c80-a4c2-11e9-9ba6-8a50d3f2cce0.png">

I'm running BRAKER with RNA-Seq data only.
How do I fix this?
Thanks!

**Comment by KatharinaHoff** [comment]
This issue should be fixed with commit https://github.com/Gaius-Augustus/BRAKER/commit/fbe3ad1d0a0dff49e21faa2aa199ffddc21298ca

DIAMOND is used instead of BLAST - if available - to filter the gene set that is predicted by GeneMark for training AUGUSTUS with nonredundant genes. Thus, it is used even if RNA-Seq is the only source of evidence.
Katharina

**Comment by msinghgb** [comment]
Thanks, Katharina!

**Comment by lfaino** [comment]
Hi @KatharinaHoff ,
i get the same error when i run BRAKER in a singularity image but the line now is 2363...
can you please help?
Cheers
Luigi

**Comment by KatharinaHoff** [comment]
This is fixed with commit https://github.com/Gaius-Augustus/BRAKER/commit/7d6f4e55badca0751d34909d152d22aae57d53fb 
Thx.
Katharina

**Comment by lfaino** [comment]
Hi @KatharinaHoff 
i did clone the repository yesterday and i get this error. 
Cheers
Luigi

**Comment by lfaino** [comment]
I saw that you made new change. I will test them

thanks
