### ISSUE TITLE
invalid source key: RM

### ISSUE THREAD

**Issue by RenscoHogers** [Gaius-Augustus/BRAKER#591]
Hi all,

I am currently using the new braker3 docker image, but I have run into the following issue. Namely an error during etraining with CRF enabled. Looking into the error file, I got this error message:
/usr/bin//etraining: ERROR
        FeatureCollection::esource: invalid source key: RM

Seemingly the same issue as was reported in #325.

Is there a way to avoid this?

Here is the used command:
`singularity exec --mount type=bind,src=$dir braker3_test.sif braker.pl --species=$species_name --workingdir=/braker3_out/ --nice --threads=48 --gff3 --crf --GENEMARK_PATH=/GeneMark-ETP/bin --PROTHINT_PATH=/ProtHint/bin --genome=$masked_genome --bam=$bam_file --prot_seq=OrthoDB/odb11v0_all_og_fasta.tab`

**Comment by KatharinaHoff** [comment]
Please disable crf for now. 

It's a known issue in Augustus, @MarioStanke has fixed it at https://github.com/Gaius-Augustus/Augustus/issues/370 . That code is not in the Augustus Debian package, yet, because there has not been a recent Augustus release.

@LarsGab we could compile Augustus from GitHub in the container to get around it... what do you think?

**Comment by LarsGab** [comment]
Yes, I think it might be a good idea to always use the latest version of Augustus, I'll try to add it to the container as soon as possible.

**Comment by spoonbender76** [comment]
Is CRF still disabled in container? 

I tried the latest container following the [#container](https://github.com/Gaius-Augustus/BRAKER?tab=readme-ov-file#container) part of user guide. 

For CRF testing, I added `--crf` in test1.sh/test2.sh/test3.sh. They all failed with `/errors/crftraining.stderr` simply saying `Segmentation fault (core dumped)`. It failed on my real data as well. The same issue have been reported and fixed in [Augustus#370](https://github.com/Gaius-Augustus/Augustus/issues/370) and [BRAKER#557](https://github.com/Gaius-Augustus/BRAKER/issues/557).

**Comment by KatharinaHoff** [comment]
This is likely resolved. I recently made a new docker container where the crf-related segmentation fault should be solved by pulling the latest augustus.
