### ISSUE TITLE
Problems with Braker2/3 results

### ISSUE THREAD

**Issue by tberthelier** [Gaius-Augustus/BRAKER#606]
Hello,
I'm writing to share my BRAKER3 data and ask for your advice and opinion. 
I annotated the genome of the same plant with BRAKER3 with RNA-seq data, with BRAKER3 without RNA-seq data and with BRAKER2 without RNA. 
Thus, with BRAKER2 in the augustus files (aa and gff3), I get 63782 sequences. With BRAKER3 with RNA-seq, I get 55875. With BRAKER3 without RNA, I get 65264. So I get big differences. I would like to know if these differences are normal, and I would like to be able to explain them in all cases.
Concerning BRAKER3, as explained in  #582 the post, I can't use the braker output files from TSEBRA. Indeed, .aa and gff do not contain the same number of genes and some features do not appear.

I am available if you need any clarification or if you need particular files.
Thank you in advance for your explanations and advice. Thank you for your work.

Sincerely

Thomas.

**Comment by tberthelier** [comment]
Hello,
Did you have time to look at my problem? I would like to have your opinion so I can continue my research. 
Thank you in advance for your help,
Sincerely,
Thomas.

**Comment by LarsGab** [comment]
Hi,

if I understand correctly, you are comparing running BRAKER v.2.xx.xx with running BRAKER v.3.xx.xx ? Did you use protein evidence for all your runs?

Regarding the comparison without RNA-Seq: In the case that you compared BRAKER v.2.xx.xx to the `braker.gtf `output from BRAKER v.3.xx.xx., note that we add transcripts predicted by GeneMark-EP+ that have high support by protein evidence to the `augustus.hints.gtf` to generate `braker.gtf`. This might account for the additional sequences. 

When you use BRAKER v3.xx.xx with proteins and RNA-Seq data, you are running an entirely different workflow and may obtain a different gene set than the other runs.. The 'low' number of genes might be due to the last step of the pipeline, where we combine the GeneMark-ETP and the Augustus predictions using TSEBRA. Here, we only include those transcripts in the result with very high support by the RNA-Seq and protein evidence. In some cases, this filtering step can be too strict. If that is the case for you, you want to consider using the Augustus prediction (Augustus/augustus.hints.gtf) as your gene set. 

The problem with the GFF file has been fixed in the latest release of BRAKER (v3.0.3).

Best,
Lars

**Comment by tberthelier** [comment]
Hello,
Sorry for the late response,
Thank you for the explanations. 

Have a nice day,

Thomas.

**Comment by tberthelier** [comment]
Oh, for your question about the protein evidence. Yes, I use the same set of protein evidence for all my runs.

**Comment by tberthelier** [comment]
Hello,
For your question about the protein evidence. Yes, I use the same set of protein evidence for all my runs.
I just want to ask you about the comparison of the augustus files. Indeed, I get 63078 predicted proteins with BRAKER3 without RNA (only the protein evidence set) and 53790 with BRAKER3 with RNA and the protein evidence set. There is a difference of about 10 000 predicted proteins. I'd like to know if this difference is normal and, above all, how to explain it.
Thank you in advance for your help,
Have a nice day,
Thomas.

**Comment by KatharinaHoff** [comment]
The difference arises from data processing differences in BRAKER2 and BRAKER3, and also from differences in evidence. It can happen that this difference is 10.000 proteins, yes. I would continue to work with the gene set that has better BUSCO/OMArk scores.
