### ISSUE TITLE
Consultation on the prediction of small peptide genes by Braker software

### ISSUE THREAD

**Issue by XK4959** [Gaius-Augustus/BRAKER#651]
Hello author:

I would like to ask some questions about the software to predict small peptide genes:
1. Is there a filtering parameter in the software that treats ORFs with <100 codons as nonsense, or something similar to that?
2. Does the software have any preference for small peptide gene prediction? What kind of parameters or input and output are conducive to predicting more and more accurate small peptide genes?
3. Does the docker version of braker3 not be able to use the chain-specific parameter, will the prediction of small peptides be helpful after adding this parameter?
4. Do you have any recommendations or thoughts on the gene structure annotation of small peptide genes?

Looking forward to your reply!
I wish you success in your research and a happy life!

xinlong
2023.07.08

**Comment by KatharinaHoff** [comment]
For each species, Augustus has a parameter in the corresponding parameter file. By default, it looks like this:

/Constant/min_coding_len              201

This means the minimal length of any predicted coding sequence for Augustus is (if this parameter was not manually altered) 201 nucleotides, corresponding to 67 amino acids.

With this parameter, AUGUSTUS is obviously not particularly suitable for the prediction of small peptide genes, regardless the provided evidence for these genes.

The parameter is set to this value because if you lower it, false positive prediction of short genes increases.

BRAKER3 should not have problems with using chained evidence in the docker container, @LarsGab please confirm.

I am not specialized on the prediction of short peptide genes and regrettably have no further advice for that particular field.

**Comment by XK4959** [comment]
Ok thank you for your reply!

I plan to adjust the size of this parameter (/Constant/min_coding_len 201) and then use transcriptome data to filter false positive results, which may be better.
Which file is this parameter in? Where will it exist in docker?

Good luck!
Xinlong

**Comment by KatharinaHoff** [comment]
If you execute in Docker, then species parameter folders will reside in /opt/Augustus/config/species . If you execute in singularity, that folder will have been copied either to your home directory (~/.augustus) or to the working directory where you executed the container.

**Comment by KatharinaHoff** [comment]
I assume that this issue is resolved. Please re-open if you have further questions.
