### ISSUE TITLE
several cds for each single gene

### ISSUE THREAD

**Issue by ardy20** [Gaius-Augustus/BRAKER#685]
Hello Braker3 developers

We checked the cds file and noticed that we get several cds (with t1, t2, t3...... suffix) for a single gene. Obviously, they have different length which might suggest the inaccurate intron prediction.

The question is how to choose the best cds for the subsequent analyses such as whole genome duplication, Ks analysis etc.

Should we keep the longest cds from each gene? Doesn't the built-in TSEBRA select the best prediction?

Regards

**Comment by LarsGab** [comment]
Hi,

BRAKER can predict multiple transcript isoforms for each gene due to alternative splicing. Similarly, TSEBRA can choose multiple isoforms when they have equal support from extrinsic evidence. If you prefer just one isoform per gene, you might consider selecting the longest one (e.g. with [get_longest_isoform.py](https://github.com/Gaius-Augustus/TSEBRA/blob/main/bin/get_longest_isoform.py)). However, the choice depends on your downstream application of the annotation

Best, Lars
