### ISSUE TITLE
Busco and number of genes when use the protein support file (in Braker3)

### ISSUE THREAD

**Issue by ardy20** [Gaius-Augustus/BRAKER#708]
Hello Developers

We have tried to use Busco to test the completeness of an Australian wild rice genome before and after annotation with Braker3 (with RNA-seq support from the leaves). The genome quality was high (with Hifi data) at chromosome-level. The genome showed a Busco value of +99.5 before annotation. After annotation with Braker3 , we used the annotated protein output file coming from Braker3 to test the Busco (with Virdiplantae dataset) and it showed a reduced value of 65% of complete single genes. 

We tried to improved the annotation quality (this wild rice with Braker3) by addition of Virdiplantae or rice annotated protein file (on top of RNA-seq support. It improved the Busco level back to 95% but the number of genes and CDS significantly reduced (from 52K to 32K).

My questions are: 

1) Is Busco a good test to assess the quality of annotation (using proteins file generated by Braker3)? 
2) Why the number of genes/CDS gets reduced when we use a protein dataset like virdiplantae or rice annotated protein?

Regards

**Comment by KatharinaHoff** [comment]
BUSCO is a tool to measure sensitivity with respect to a rather small set of core genes in a clade. We commonly use it. If you want to measure sensitivity with respect to a larger number of genes, try OMArk.

AUGUSTUS and GeneMark have a tendency to overpredict genes. TSEBRA tries to fix this based on evidence, but if there is too little evidence, too many transcripts may be dropped. BUSCOs often have enough evidence, that's why the BUSCO number went up when you added the plants OrthoDB parition.

I usually re-run TSEBRA enforcing the best gene set (either augustus.hints.gtf or genemark.gtf) according to BUSCO if this happens. You find instructions at https://github.com/KatharinaHoff/BRAKER-TSEBRA-Workshop/blob/main/GenomeAnnotation.ipynb .

Rice was previously reported to have ~35K genes. 32K doesn't seem so far off. You will likely have an inflated gene count if you re-run TSEBRA as suggested.

**Comment by ardy20** [comment]
Thanks!

**Comment by KatharinaHoff** [comment]
Hardmasking means nucleotides are ignored.

Augustus can initiate a gene in an unmasked region and extend into the softmasked region.

We recommend softmasking.

**Comment by ardy20** [comment]
Could you please guide how to set the weight for Augustus and Genmarks in
configuration file of TSEBRA?

**Comment by KatharinaHoff** [comment]
I usually do not alter the parameters. There's a command line option to enforce entire gene sets. The linked jupyter notebook has a command example.

**Comment by ardy20** [comment]
Thanks!
