### ISSUE TITLE
Question regarding augustus.hints.gff

### ISSUE THREAD

**Issue by fuesseler** [Gaius-Augustus/BRAKER#761]
Hello,
Thanks for developing BRAKER3 it has been a game-changer in my annotation efforts :)

I have a question regarding understanding the contents of augustus.hints.gff properly: Does this file only contain gene models that are supported by some extrinsic evidence (similar to genemark_supported.gtf) , or also "pure" ab initio models?

( Background is that in order to integrate my BRAKER3 results with projections from TOGA, I am trying to use EvidenceModeler .. but up until now have only managed to make the "combined" annotation worse. So I am currently testing whether adding in the "supported" gene models like genemark_supported.gtf with a higher weight will improve the result and wondering whether I can use the augustus.hints.gff in the same way or not ) 

Grateful for any advice in advance!

**Comment by KatharinaHoff** [comment]
The output of BRAKER contains both evidence supported and ab initio predictions. You cannot tell them apart in the gtf file.

Please note that the current output is braker.gtf, not augustus.hints.gtf, anymore.

Our own results with EvidenceModeler were discouraging... that's why we made TSEBRA. Figure 3 of the TSEBRA paper: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04482-0/figures/3

**Comment by fuesseler** [comment]
Thank you for the explanation! I was still running braker version 3.0.3 and besides the final braker.gtf it was providing the augustus.hints.gtf in the Augustus subfolder. I should probably update to the newest release soon.

I hadn't even considered TSEBRA to integrate BRAKER3 with TOGA projections, but now this makes total sense to try! I will give it a go. Thank you for the suggestion!
