### ISSUE TITLE
Braker3 optimize_augustus.pl process does not terminate

### ISSUE THREAD

**Issue by kataksk** [Gaius-Augustus/BRAKER#829]
Hello Braker3 Team,

I am currently encountering an issue with the `optimize_augustus.pl` script in Braker3, which has been running for over 10 days without termination for a specific genome dataset. I am using the same version of Braker3 that I have successfully used with another dataset where all processes completed within a few days.

Here are the details:
- **Braker3 version**: 3.0.8
- **Command used**: 
`braker.pl --genome=$genome --prot_seq=$prot_seq --workingdir=$work_dir --threads $threads --bam=/data/CLEAN.sorted.bam > /wd240509/braker3_out`

The `optimize_augustus.pl` step has been running excessively long compared to another species' annotation under the same conditions, which completed as expected.

I am wondering if there might be an issue with certain types of input datasets. Could there be a known issue or a potential debug tip you could suggest?

I have attached the log files from the running process (i.e. braker.log and optimize_augustus.stdout). Please let me know if you need any more information to help diagnose the problem.
[log.zip](https://github.com/Gaius-Augustus/BRAKER/files/15383645/log.zip)

Thank you for your assistance.

Best regards,
Kosuke

**Comment by KatharinaHoff** [comment]
optimize_augustus.pl will not run forever. It is an optimization script, and the number of optimization rounds is limited. However, it can take different amounts of time, because a larger number of meta parameters is optimized, and they depend on each other. Sometimes, this converges fast, sometimes it takes a very long time. I must admit that a runtime of ~10 days on 40 threads is excessive. I am wondering whether the log of optimize_augustus.pl was really touched within the past couple of days, or whether the process is really stuck. Can you check the time stamp? The time stamp that I see is May 11th, and the optimize_augustus job only started on May 11th - that would be totally ok, but you are writing that it has been running for a very long time - so I am wondering what exactlty is happening.

**Comment by kataksk** [comment]
Thank you for your prompt response.

1. The timestamp of the optimize_augustus.stdout file shows it was last modified on May 11th.
2. The timestamp of the braker.log file indicates it was last modified on May 11th.

Given these timestamps, it appears that the files have not been updated since May 11th.
Based on this information, it seems that the process may be stuck.

**Comment by kataksk** [comment]
I rerun the pipeline with the same parameters on the same machine, and all the process has been completed this time. I'm closing this session. Thanks.
