### ISSUE TITLE
More proteins than transcripts in BRAKER annotation results

### ISSUE THREAD

**Issue by xeniaroda** [Gaius-Augustus/BRAKER#865]
I am performing an annotation of a de novo algae assembly using BRAKER. I found that my results (in the file `braker.gtf`) show more proteins (36 more) than transcripts, which seems unusual. Below are the details:

# BRAKER command: 

`docker run -it --user root -v /media/Project/annotation/braker/protein_fasta_viridiplantae_2024:/wd -v /media/Project/annotation/edta_softmask/:/rvd --rm teambraker/braker3:latest braker.pl --genome=/rvd/Final_assembly_softmasked.fasta --prot_seq=/wd/uniprotkb_taxonomy_id_33090_AND_reviewe_2024_10_01.fasta --species=Species_ACC4J --threads 32 --workingdir=/wd/Modify
`

I counted transcripts and proteins using the following commands:
# Counting transcripts
awk '$2 == "AUGUSTUS" && $3 == "transcript"' braker.gtf | wc -l

# Counting proteins
grep ">" braker.aa | wc -l

Results:

    Transcripts: 9602
    Genes: 9471
    Proteins: 9638
    CDS: 102575
    Exons: 102575

I expected the number of proteins and transcripts to match. Could the discrepancy be due to repeated proteins? How can I check for this?

Thanks in advance for your help!

**Comment by xo2003** [comment]
That is because your counting is restricted to 'AUGUSTUS'; however, annotation sources do not come only from 'AUGUSTUS'. You can use `cut -f 2 braker.gtf | sort | uniq` to check this.

I only found issue like this...
![image](https://github.com/user-attachments/assets/932ac50c-83a6-4472-82ea-146cdb7118f3)
Although it doesn't cause any trouble, the mRNA feature of GeneMark.hmm3 should be removed.

**Comment by xeniaroda29** [comment]
> That is because your counting is restricted to 'AUGUSTUS'; however, annotation sources do not come only from 'AUGUSTUS'. You can use `cut -f 2 braker.gtf | sort | uniq` to check this.
> 
> I only found issue like this... ![image](https://private-user-images.githubusercontent.com/136870182/373541983-932ac50c-83a6-4472-82ea-146cdb7118f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMzgwNTUsIm5iZiI6MTcyODAzNzc1NSwicGF0aCI6Ii8xMzY4NzAxODIvMzczNTQxOTgzLTkzMmFjNTBjLTgzYTYtNDQ3Mi04MmVhLTE0NmNkYjcxMThmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxMDI5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjJhYWYwMjRkZmYyMjM0OTMzYzMxMTNiOGVhYzljMTY0Yzc3NzAxNjg5MmY1NmQ0MzM1M2NhNjA1NTk5ZTg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dPGoU6cBMpB5Zxk2xyaplf7kxWnREQYxHrD1gLfCSDQ) Although it doesn't cause any trouble, the mRNA feature of GeneMark.hmm3 should be removed.

Thank you for the suggestion! I have now resolved the issue. As you pointed out, the discrepancy was due to the presence of proteins annotated by both AUGUSTUS and GeneMark.hmm3. After reviewing the annotations, I found that indeed the braker.gtf file contains entries from both tools. Similarly, the `braker.aa` file also includes annotated proteins from both AUGUSTUS and GeneMark.hmm3. My approach moving forward will be to focus specifically on the AUGUSTUS results in the AUGUSTUS folder to ensure consistency. Thanks again for the help!
