### ISSUE TITLE
BAM merging

### ISSUE THREAD

**Issue by mictadlo** [Gaius-Augustus/BRAKER#89]
Hi,
I want to use BRAKER for a plant genome.  We have tissue-specific RNA-seq reads for flower, leaf, meristem, roots and even the whole plant. All RNA-seq data comes from NCBI, and for example, the root data contains 14 paired-end reads:

- https://www.ncbi.nlm.nih.gov/sra/?term=SRR5144669
- https://www.ncbi.nlm.nih.gov/sra/?term=SRR5144670
- https://www.ncbi.nlm.nih.gov/sra/?term=SRR5144671
- https://www.ncbi.nlm.nih.gov/sra/?term=SRR5144672
- https://www.ncbi.nlm.nih.gov/sra/?term=SRR5144673
- https://www.ncbi.nlm.nih.gov/sra/?term=SRR5144674
- https://www.ncbi.nlm.nih.gov/sra/?term=SRR5144675
- https://www.ncbi.nlm.nih.gov/sra/?term=SRR5144676
- https://www.ncbi.nlm.nih.gov/sra/?term=SRR5144677
- https://www.ncbi.nlm.nih.gov/sra/?term=SRR5144678
- https://www.ncbi.nlm.nih.gov/sra/?term=SRR5144679
- https://www.ncbi.nlm.nih.gov/sra/?term=SRR5144680
- https://www.ncbi.nlm.nih.gov/sra/?term=SRR5144681
- https://www.ncbi.nlm.nih.gov/sra/?term=SRR5144682

Would it better to use BRAKER for each individual BAM file as shown below?
```
> braker.pl --bam=SRR5144669.bam,SRR5144670.bam,SRR5144671.bam,SRR5144672.bam,SRR5144673.bam,SRR5144674.bam,SRR5144675.bam,SRR5144676.bam,SRR5144677.bam,SRR5144678.bam,SRR5144679.bam,SRR5144680.bam,SRR5144681.bam,SRR5144682.bam,.....
```
Or would it better to do the following merging approach for each tissue?
```
> samtools merge roots.bam SRR5144669.bam SRR5144670.bam SRR5144671.bam SRR5144672.bam SRR5144673.bam,SRR5144674.bam SRR5144675.bam SRR5144676.bam SRR5144677.bam SRR5144678.bam SRR5144679.bam SRR5144680.bam SRR5144681.bam SRR5144682.bam
> samtools merge wholeplant.bam SRR1043177.bam SRR1043178.bam SRR1043179.bam
...
> braker.pl  --bam roots.bam,wholeplant.bam,... 
```

Thank you in advance,

Michal

**Comment by KatharinaHoff** [comment]
Please merge the bam files. Consider sampling with VARUS, instead of using
all data.

Katharina

**Comment by mictadlo** [comment]
Just double checking, would this merging approach for each tissue be the best?
```
> samtools merge roots.bam SRR5144669.bam SRR5144670.bam SRR5144671.bam SRR5144672.bam SRR5144673.bam,SRR5144674.bam SRR5144675.bam SRR5144676.bam SRR5144677.bam SRR5144678.bam SRR5144679.bam SRR5144680.bam SRR5144681.bam SRR5144682.bam
> samtools merge wholeplant.bam SRR1043177.bam SRR1043178.bam SRR1043179.bam
...
> braker.pl  --bam roots.bam,wholeplant.bam,... 
```

VARUS sounds interesting, but NCBI has various tissue-specific RNA-Seq data for our plant. However, VARUS expects a species name. Is it possible that VARUS could miss some of the tissues because it might have enough data?

If VARUS would have enough data, do you think it would be better to run MarkDuplicates and remove aligned reads with lower than 40 quaily score in order to unique mapped reads? 

Thank you in advance,

Michal

**Comment by KatharinaHoff** [comment]
BRAKER _can_ merge the bam files for you, i.e. you could provide all of them as arguments to --bam. However, I _recommend_ that you merge all bam files into one single file ("all.bam" or similar) prior calling BRAKER. Saves you the trouble of digging in log files if anything goes wrong during the bam merge.

Yes, VARUS could miss some of the tissues. But it likely won't matter. Because VARUS tries to sample a good coverage for all loci. If there is already a good coverage, and let's say "root", which was missed, also expresses the same genes as some other tissues did already, then it doesn't matter much, whether "root" was skipped.

I haven't filtered the output file of VARUS (actually a hints file is available, then, not a bam file), it so far worked well for a range of species (for example listed in the VARUS preprint on bioarxive).
