### ISSUE TITLE
flanking_DNA uninitialized for UTR=on run

### ISSUE THREAD

**Issue by michaelkarlcoleman** [Gaius-Augustus/BRAKER#98]
Is this value supposed to be computed by the script?  Or perhaps it's required on the command-line in this case?

Mike

```
Use of uninitialized value $flanking_DNA in concatenation (.) or string at /packages/braker/2.1.4/scripts/braker.pl line 9623.
ERROR in file /packages/braker/2.1.4/scripts/braker.pl at line 9630
Failed to execute: perl /gpfs/packages/augustus/3.3.3/scripts/gff2gbSmallDNA.pl /gpfs/projects/hpcrcf/mkc/mcurrey/braker/braker/genes.gtf /gpfs/projects/hpcrcf/mkc/mcurrey/braker/braker/genome.fa  /gpfs/projects/hpcrcf/mkc/mcurrey/braker/braker/utr.gb --good=/gpfs/projects/hpcrcf/mkc/mcurrey/braker/braker/bothutr.lst 1> /gpfs/projects/hpcrcf/mkc/mcurrey/braker/braker/gff2gbSmallDNA.utr.stdout 2> /gpfs/projects/hpcrcf/mkc/mcurrey/braker/braker/errors/gff2gbSmallDNA.utr.stderr!
```

```
braker.pl \
    --species=ptae_an \
    --genome=ptae_pilon2_assem_upcase.fasta.masked \
    --bam=pta_rna_plus.bam,pta_rna_minus.bam \
    --stranded=+,- \
    --UTR=on \
    --softmasking \
    --cores "${SLURM_CPUS_PER_TASK:-1}" \
    --AUGUSTUS_CONFIG_PATH=${PWD}/augustus-config \
    --AUGUSTUS_BIN_PATH=${AUGUSTUS_BIN_PATH} \
    --AUGUSTUS_SCRIPTS_PATH=${AUGUSTUS_SCRIPTS_PATH} \
    \
    --useexisting \
    --verbosity=4 \
    --nocleanup \
#
```

**Comment by michaelkarlcoleman** [comment]
From the code, it appears that this error (probably) only happens if `--useexisting` is specified.  As a workaround, omit this flag and either use an unused species name or zap the species directory in `AUGUSTUS_CONFIG_PATH`.

**Comment by KatharinaHoff** [comment]
The size of flanking region is generally computed in the BRAKER run that is used to train the "normal" parameters (i.e. not necessarily the UTR parameters). If you later call BRAKER to train the UTR parameters, e.g. on the basis of an existing parameter set and an existing gene set, then it was intended that you go into the log file of your original BRAKER run and check the size of the flanking region in order to pass it as parameter to BRAKER, so that it's the same in the original run and in the UTR training run.

I have now implemented that a new flanking region size is computed from the GTF file that is used as "template" to start building UTR training examples in case it's undefined. That makes a separate training run for UTR training different from if the UTR training was performed during the original BRAKER run. It won't do much harm, though. You should just be aware that it's a different thing.

https://github.com/Gaius-Augustus/BRAKER/commit/440f3b83d69582fdd5b1b55b247024e5fb544802

**Comment by KatharinaHoff** [comment]
That is quite confusing at the moment. I tried to at least improve the documentation about useexisting and additional UTR training in commit https://github.com/Gaius-Augustus/BRAKER/commit/042b3cff42f07743c7d0d4fbc9c7cf9eaeed0b4f .

Katharina
